### ISSUE TITLE
Move OrderOverviewComponent from shared to order folder

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#13403] opened 2021-08-04 19:09 UTC
`OrderOverviewComponent` is in `shared` folder. We will move it inside `order` folder first, then move it to `order` lib. And make `checkout` lib have cms mapping map from ConfirmationOrderOverview to OrderOverviewComponent.

**Comment by WeizhengSap** [comment] 2021-08-04 20:18
Change the default cms mapping maybe bring breaking changes. If so, then this ticket can be done in 5.0.

**Comment by plabadie** [comment] 2021-08-04 21:28
We already have this ticket for 5.0: GH-13324
Perhaps close this ticket if it becomes a duplicate of GH-13324

**Closed as completed** 2021-10-26 18:17 UTC
Labels: MVP, cart-lib, order-lib
