### ISSUE TITLE
[Revert change] B2B MyCompany Organization Page Visible to Anonymous/Non-Admin Users

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8865] opened 2020-09-10 09:59 UTC
**Steps to Reproduce:** 

1. As an anonymous user navigate directly to b2b storefront organization page. 
1.a URL:  http://spartacus-dev4.eastus.cloudapp.azure.com:4201/powertools-spa/en/USD/organization
2. Login as a non-admin user. 
2.a. (i.e. mark.rivers from sample data)
3. Navigate directly to b2b storefront organization page. 

**Actual Results**
1. Organization page is visible and links thereof are available to anonymous user. 
3. Same as Step 1. 

**Expected Results:** 
1. Redirect to login. Anonymous users must not see this page as it reveals the available components of an organization.
1.a. Doesn't conform with product security standard SEC-248.

3. Same as step 1.

**Comment by giancorderoortiz** [comment] 2020-09-10 10:11
![Screen Shot 2020-09-10 at 6 07 56 AM](https://user-images.githubusercontent.com/46171897/92716218-85601a80-f32c-11ea-827c-03ad6bbe8bab.png)
![Screen Shot 2020-09-10 at 6 09 06 AM](https://user-images.githubusercontent.com/46171897/92716219-85601a80-f32c-11ea-9865-97b6ce34aed1.png)

**Comment by kacperknapik** [comment] 2020-10-16 12:42
Duplicate of #8801

**Comment by giancorderoortiz** [comment] 2020-10-16 12:57
Pending internal discussion.

**Comment by Pucek9** [comment] 2020-10-16 13:26
As  I'm not permitted to close that duplicate ticket, pasting details from original [issue](https://github.com/SAP/spartacus/issues/8801):
![image](https://user-images.githubusercontent.com/8040837/96263691-9226fc80-0fc3-11eb-9fcd-eb057e6b0819.png)

**Comment by tobi-or-not-tobi** [comment] 2020-10-16 14:14
I've aligned this issue with @meeque and we agree that the analysis of https://github.com/SAP/spartacus/issues/8801#issuecomment-686448047 is correct. Quick summary on the general statement: 
- This is predominantly an experience issue, not a security threat
  - the OCC API is guarded, you cannot crud any secure data without an access token
  - CMS components are guarded, you can restrict exposing them in OCC CMS
  - CMS pages are **not** guarded, but will only expose page meta info (i.e. title) and not actual content
- Spartacus has already done enough to guard routes/components where it can. The real issue is in OCC CMS (CMSX-8491).

Regarding this case, we have already guarded the CMS components in the sample data of the /organization landing page. That is beyond my personal ambition, but now that we have it, we can keep it like that. In addition, we could introduce a paragraph component on the page, saying that you need to login to see the content. If we can role the restricted content back, i'd be happier; less sample data to worry about, and less complexity in edge caching to distinguish the page for different users. 

@meeque / @giancorderoortiz please close accordingly.

**Comment by meeque** [comment] 2020-10-16 18:12
I agree with @tobi-or-not-tobi. In this specific case, there is a negligible confidentiality impact. An unauthorized user (including the anonymous user) can merely see contents that have no strict confidentiality requirements. E.g. the user sees the banners and can follow the links, but guards in the OCC API prevent then to see anything confidential.

The situation might be slightly different for other CMS pages, if those actually contain confidential data. In that case, there is very little Spartacus can do about it. An attacker could bypass any Spartacus-specific security controls by using the OCC CMS API directly. Thus, such security controls must be implemented by the OCC API instead, see CMSX-8491.

**Comment by giancorderoortiz** [comment] 2020-10-18 19:09
ok

**Comment by Xymmer** [comment] 2020-10-19 12:42
Let's put it back to the way it was, it's weird seeing a blank page
We could add a note in the page in the future about why they are seeing this. 
they'd also have to know the url to get there

**Comment by giancorderoortiz** [comment] 2020-10-19 16:03
This is what we see now with anonymous or non-admin user(develop branch Oct 18):

![Screen Shot 2020-10-19 at 12 01 35 PM](https://user-images.githubusercontent.com/46171897/96476209-ebc93a00-1202-11eb-8d17-e07bb3017277.png)
 
Given @meeque gave the green light, I guess we can put it back the way it was.

**Comment by Xymmer** [comment] 2020-10-26 11:51
Revert so that my company page appears no matter the permissions, but user has to log in to do anything

**Comment by WeizhengSap** [comment] 2020-12-01 14:31
In `spartacussampledata`, open file `cms-responsive-content.impex` inside `powertoolsContentCatalog` folder. Comment out these 2 lines (line 654-655):
```
INSERT_UPDATE CMSUserGroupRestriction;$contentCV[unique=true];uid[unique=true];name;userGroups(uid);includeSubgroups;components(&componentRef)
;;MyCompanyLinkAdminGroupRestriction;My Company Link Admin Group Restriction;b2badmingroup;true;BudgetsHomeLink,CostCentersHomeLink,UnitsHomeLink,UsersHomeLink,UserGroupsHomeLink,PurchaseLimitsHomeLink

```

Then the banner components will be displayed even for anonymous users.
![Screen Shot 2020-12-01 at 9 38 04 AM](https://user-images.githubusercontent.com/44440575/100754345-fc9bcc80-33b8-11eb-9cc2-0c21076fee10.png)

**Comment by psmul** [comment] 2020-12-04 09:04
PR ready:
https://github.tools.sap/cx-commerce/spartacussampledata/pull/154

**Comment by psmul** [comment] 2020-12-08 06:25
Sampledata has been merge, so we only need to restart servers to apply changes. I believe @giancorderoortiz will handle that part.

**Comment by giancorderoortiz** [comment] 2020-12-14 00:14
Updated qa back server with latest sample data version. 
I see this revert has now been applied successfully. 

![Screen Shot 2020-12-13 at 7 11 07 PM](https://user-images.githubusercontent.com/46171897/102028289-6cc22f00-3d77-11eb-9b8a-221d551febe1.png)

**Closed as completed** 2020-12-14 20:04 UTC
Labels: bug, team/gladiators
