### ISSUE TITLE
Global Message Configuration is not working regarding Timeout

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#15517] opened 2022-03-31 15:24 UTC
**Describe the bug**
I added a custom Configuration for Global Message. According to the documentation [here](https://sap.github.io/spartacus-docs/global-messages/), it says: 

"The global messages model is used in projects/core/src/global-message/config/global-message-config.ts to set the time after which the message should disappear. If you omit a particular type in the configuration, the messages for that type will not disappear."

My Custom config:

```
export function globalMessageConfigFactory(): GlobalMessageConfig {
  return {
    globalMessages: {
      [GlobalMessageType.MSG_TYPE_CONFIRMATION]: {
        timeout: 3000,
      },
      [GlobalMessageType.MSG_TYPE_ERROR]: {
        timeout: 7000,
      },
      [GlobalMessageType.MSG_TYPE_WARNING]: {
        timeout: 7000,
      },
    },
  };
}
```

As I understand the docs, now messages of the type `info` should NOT disappear. I tried to add the configuration via `ConfigModule.withConfigFactory(globalMessageConfigFactory)` or via config provider `provideConfigFactory(globalMessageConfigFactory),`. 

No matter how I add it, when debugging, the config still seems to be the default config coming from the spartacus code..

**Tell us the version of Spartacus**
- Library version: 4.3

**To Reproduce**
Steps to reproduce the behaviour:
1. Define and provide custom global message config which does not have the message type `GlobalMessageType.MSG_TYPE_INFO` defined
2. Make a global message appear
3. Notice that the message disappears after 3seconds (default value from default global message config)

**Expected behaviour**
According to custom config and docs, the message should stay forever

**Screenshots**
<img width="857" alt="image" src="https://user-images.githubusercontent.com/3381820/161091632-22259ce4-c7b5-4bdb-af98-b55b762e2d18.png">

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Additional Information**
It seems to work, when defining another custom value like a bigger timeout, but I want to keep the messages there per default.. In that case, the config property for a specific message time seems to get added again from the default config

**Comment by BenjaminEmiliani** [comment] 2022-03-31 20:19
@janwidmer Your understanding of the documentation is not wrong, yet it seems you may be correct, the default configuration for all four message types are loaded into the application and when you `provideConfigFactory(globalMessageConfigFactory)` it only overrides existing values. 

More investigation to ensue. At the moment the only alternative I can offer you is which is not part of the documentation is to set the type configuration you wish to exclude to `undefined`

```export function globalMessageConfigFactory(): GlobalMessageConfig {
  return {
    globalMessages: {
      [GlobalMessageType.MSG_TYPE_CONFIRMATION]: {
        timeout: 3000,
      },
     [GlobalMessageType.MSG_TYPE_INFO]: undefined,
      [GlobalMessageType.MSG_TYPE_ERROR]: {
        timeout: 7000,
      },
      [GlobalMessageType.MSG_TYPE_WARNING]: {
        timeout: 7000,
      },
    },
  };
}
```
Not as clean as a solution but it seemed to work on a sample application on my end

**Comment by janwidmer** [comment] 2022-04-01 04:21
@BenjaminEmiliani thanks for confirming my investigations. Setting it to `undefined` seems to lead to a console exception though, therefore, I guess, I will just set the timeout value to a very big value to basically show it "forever"..

**Comment by janwidmer** [comment] 2022-04-01 12:31
@BenjaminEmiliani setting just the `timeout` property to `undefined` seems to work. Thanks for that workaround

**Comment by BenjaminEmiliani** [comment] 2022-04-01 12:46
@janwidmer No problem, do try something before leaving it with `{timeout: undefined}`. At least in my sample application, if that is the config for a certain message type, after it is emitted it stays indefinitely, but the problem is so do other message types after it even if they have a defined timeout. Can you confirm this?

**Comment by Xymmer** [comment] 2022-04-07 19:13
Hi @janwidmer, closing as it looks like answer provided, but reopen/let me know if not.

**Closed as completed by Xymmer** 2022-04-07 19:13 UTC

**Comment by janwidmer** [comment] 2022-04-08 06:39
@BenjaminEmiliani I am not sure if I understand your suggestion, what I should additionally try?

@Xymmer mmh the suggested solution is a workaround. It seems there is a bug after all, because what is written in the docs does not work. So either, the docs would need to be updated with the suggestion of @BenjaminEmiliani or the bug would need to be fixed, so that it works like described in the docs.. So in my opinion, the ticket is still valid and should stay open..
