### ISSUE TITLE
Blank page if session has expired on reload [was set to 5.0]

### ISSUE THREAD

**Issue by thebackfisch** [SAP/spartacus#13721] opened 2021-09-15 12:51 UTC
**Describe the bug**
If you refresh the page and the access and refresh token are expired you get only a blank page.

**Tell us the version of Spartacus**
- Library version: 4.1

**To Reproduce**
1. Go to https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/login
2. Log in
3. Wait until the token expired (120sec)
4. refresh the page

**Expected behavior**
You should either be redirected to the login page if you requested a protected resource or access the site you requested.

**Additional context**
The expired token gets attached to the basesites-request, which results in a 401 return from the server. Now the application tries to load several pages (login, not-found etc) but fails to do so due to the unknown base site (server returns a 400 with message "Base site cms doesn't exist").

**Comment by Platonn** [comment] 2021-11-15 15:45
Thanks for reporting it @thebackfisch!
I could not reproduce the issue using the demo server. I refreshed 120+ sec after login. However, the /basesites call was successful. Then the call for /pages failed with 401 and I was redirected to the login page (all as expected):
![image](https://user-images.githubusercontent.com/4001059/141810667-5be4cfc4-aa69-4076-906d-2bcb37c8de3b.png)

What is strange and worth investigating, that there are a 3 failing calls for /pages API. But that a very different issue, which has lower severity than the issue that you're reporting.

**Comment by felix-ka** [comment] 2022-04-27 17:42
I am facing the same issue with my installation and on the demo server:

![image](https://user-images.githubusercontent.com/5337941/165586843-0a02e256-1660-4549-b145-7fe6536db6e3.png)

Same steps as mentioned by @thebackfisch 

I guess the issue is that the request to the basesites occ-endpoint still contains the expired authorization bearer/token. Then the following happens:

1. Call to basesites gets denied with an http-status 401
2. This is the indicator for spartacus to revoke the token and send the user to the login page
3. In order to show the login page spartacus makes a call to the /pages occ-endpoint. In the path it requires the basesite which it could not get in the first place. So it is actually missing as you can see in the screenshot and when you compare it to a successful call to this endpoint. 

Not sure if the token should not be send when fetching basesites or before the forwarding to the login page the app should make a request again to the basesites endpoint. This time without the token.

**Comment by wangzixi-diablo** [comment] 2022-05-20 04:53
one customer reports this issue via SNOW ticket, they are using 4.2, B2B storefront with CSR. 

I can also reproduce the issue in 4.2.1: https://github.com/SAP/spartacus/issues/15771

**Comment by Xymmer** [comment] 2022-05-20 13:10
tracking work in internal issue CXSPA-485

**Comment by Zeyber** [comment] 2022-05-26 15:20
Can reproduce this in `4.2.1` csr app installed with installation script. Upgrading to `4.3.4` did not seem to resolve this.

**Comment by Zeyber** [comment] 2022-05-31 10:14
This issue occurs when the `BASE_SITE` is not defined when using the installation script which means that no base sites get added to the `spartacus-configuration.module.ts`. 

- Please add a valid `BASE_SITE` string to `config.ts` before starting the installation script.
```
BASE_SITE="electronics-spa,electronics,apparel-de,apparel-uk,apparel-uk-spa"
```
OR
-  Add `baseSite` to the `spartacus-configuration.module.ts`.
```
@NgModule({
  ...
  providers: [ provideConfig(<SiteContextConfig>{
    context: {
      ...
      baseSite: ['electronics-spa', 'electronics', 'apparel-de', 'apparel-uk', 'apparel-uk-spa'],
    },
    ...
  ]
})
export class SpartacusConfigurationModule { }
```

**Comment by Xymmer** [comment] 2022-06-01 11:55
this issue will be fixed in install script in next release, and workaround posted above, so closing

**Closed as completed by Xymmer** 2022-06-01 11:55 UTC
Labels: bug, session-mgmt, Major

**Comment by felix-ka** [comment] 2022-06-01 13:05
Hi @Xymmer and @Zeyber,

Thank you for working on this issue. 
When reading the documentation on automatic multisite configuration in the [Spartacus Documentation](https://sap.github.io/spartacus-docs/automatic-context-configuration/) it states to simply not define the context.baseSite property. 

How will this work together with the work around you proposed?

Thank you and best regards
Felix
