### ISSUE TITLE
Readonly doesn't work on first render for quantity component

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#6690] opened 2020-02-24 13:31 UTC
On the cart item list with read-only quantity component it could still be modified in the input field.

How to reproduce:
- got to last checkout step
- click the quantity value
- you can modify the value through normal input or with arrows

Desired behavior:
- can't change read-only values

**Comment by tobi-or-not-tobi** [comment] 2020-04-29 11:25
seems a duplicate of #6180

**Comment by kacperknapik** [comment] 2020-05-04 12:45
Fixed in #7339

**Closed by kacperknapik** 2020-05-04 12:45 UTC
Labels: MUST, bug, quantity-box, team/asterix
