### ISSUE TITLE
B2B Scheduled Replenishment

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#5575] opened 2019-11-28 19:12 UTC
Based off of how it worked in Accelerator, how do we want to do it in Spartacus? 
Requirements: feature parity but we can try to do something better if we can.

- [ ] Estella researches approaches
- [ ] Anthony/Estella crank out a design

Questions:
- What about scheduled replenishments and quotes
- Can I convert an existing order to a scheduled replenishment?
- If I cancel a scheduled replenishment, can i bring it back? or add it back to a cart for a new ro?
- Should replenishments be listed as a tab like returned orders?

**Comment by bgambocjaviniar** [comment] 2020-08-12 22:06
closing because this is a duplicate of https://github.com/SAP/spartacus/issues/8202

**Closed by bgambocjaviniar** 2020-08-12 22:06 UTC
Labels: b2b-scheduled-replenishment
