### ISSUE TITLE
Back to list button goes to the homepage 

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#9361] opened 2020-10-15 16:41 UTC
**Describe the bug**
Back to list button goes to the homepage 

**To Reproduce**
1. log in as an approver
2. Go to the approval dashboard and open a pending order
3. Click on the Back to List button
4. Observe that you are navigated to the home page instead of the Approvals list

**Expected behavior**
The back to list button should navigate to the Order Approval list

**Screenshots**
<img width="765" alt="Screen Shot 2020-10-13 at 4 32 24 PM" src="https://user-images.githubusercontent.com/15215400/96160225-4862e700-0edb-11eb-8299-c4ae8b05a0cf.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version:  85.0.4183.121

**Comment by bgambocjaviniar** [comment] 2020-10-15 16:48
duplicate of https://github.com/SAP/spartacus/issues/9122

I suggest to pull from latest develop as I believe you're in an old branch as above been merged just yesterday

**Comment by plabadie** [comment] 2020-10-15 18:15
Indeed, this is already fixed in #9122

**Closed as completed** 2020-10-15 18:14 UTC
Labels: bug, my-company/approval-dashboard, b2b-mycompany
