### ISSUE TITLE
`ng g @spartacus/schematics:add-pwa` doesn't work

### ISSUE THREAD

**Issue by mpern-sap** [SAP/spartacus#8233] opened 2020-07-16 07:58 UTC
**Describe the bug**

The command as described in the docs [schematics][ref] doesn't work

[ref]: https://sap.github.io/spartacus-docs/schematics/

Workaround:

Re-add the schematic with the `--pwa` flag

```
ng add @spartacus/schematics --pwa
```

**To Reproduce**

```
cd spartacus-project
ng g @spartacus/schematics:add-pwa 
Cannot read property 'targets' of undefined
```

**Expected behavior**

PWA config generated

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by znikola** [comment] 2020-07-31 12:25
@mpern-sap can you please specify which CLI and yarn version are you using?

**Comment by mpern-sap** [comment] 2020-07-31 12:27
```
 % node --version                                                                                                                                                                          
v12.18.1
 % yarn --version                                                                                                                                                                          
1.22.4
 % ng --version                                                                                                                                                                             
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
Angular CLI: 10.0.2
Node: 12.18.1
OS: darwin x64
Angular: 10.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.2
@angular-devkit/build-angular     0.1000.2
@angular-devkit/build-optimizer   0.1000.2
@angular-devkit/build-webpack     0.1000.2
@angular-devkit/core              10.0.2
@angular-devkit/schematics        10.0.2
@angular/cli                      10.0.2
@ngtools/webpack                  10.0.2
@schematics/angular               10.0.2
@schematics/update                0.1000.2
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0
```

**Comment by znikola** [comment] 2020-07-31 12:28
Thank you.
Similar to https://github.com/SAP/spartacus/issues/8206, CLI v10 is not yet supported.

As a temporary workaround, please try with CLI v9.

**Comment by mpern-sap** [comment] 2020-07-31 12:31
ah sorry, I've got the two bugs mixed up.

This one is about `ng g @spartacus/schematics:add-pwa` not working, even with a compatible angular version

**Comment by mpern-sap** [comment] 2020-07-31 12:32
```
 % ng --version                                                                                                                                           
To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 9.1.11
Node: 12.18.1
OS: darwin x64

Angular: 9.1.12
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.11
@angular-devkit/build-angular     0.901.11
@angular-devkit/build-optimizer   0.901.11
@angular-devkit/build-webpack     0.901.11
@angular-devkit/core              9.1.11
@angular-devkit/schematics        9.1.11
@angular/cdk                      9.2.4
@angular/cli                      9.1.11
@angular/pwa                      0.901.11
@ngtools/webpack                  9.1.11
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.11
@schematics/update                0.901.11
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by znikola** [comment] 2020-07-31 12:39
Oh ok. Thanks for reporting it, I'll look into it.

**Comment by znikola** [comment] 2020-07-31 13:46
I was not able to reproduce the issue in a testing project that uses Angular v9 libraries.
Angular CLI v10 was installed globally, but it fell back to v9 CLI, as that was specified in the test project.

@mpern-sap can you please confirm that you were using Angular 9 libraries, and not Angular 10? 
And just to be clear, I'm not asking about the global Angular CLI version.

**Comment by mpern-sap** [comment] 2020-07-31 13:53
```
 % yarn list --depth=0
yarn list v1.22.4
├─ @angular-devkit/architect@0.901.11
├─ @angular-devkit/build-angular@0.901.11
├─ @angular-devkit/build-optimizer@0.901.11
├─ @angular-devkit/build-webpack@0.901.11
├─ @angular-devkit/core@9.1.11
├─ @angular-devkit/schematics@9.1.11
├─ @angular/animations@9.1.12
├─ @angular/cdk@9.2.4
├─ @angular/cli@9.1.11
├─ @angular/common@9.1.12
├─ @angular/compiler-cli@9.1.12
├─ @angular/compiler@9.1.12
├─ @angular/core@9.1.12
├─ @angular/forms@9.1.12
├─ @angular/localize@9.1.12
├─ @angular/platform-browser-dynamic@9.1.12
├─ @angular/platform-browser@9.1.12
├─ @angular/pwa@0.901.11
├─ @angular/router@9.1.12
├─ @angular/service-worker@9.1.12
...
```

**Comment by znikola** [comment] 2020-07-31 14:07
Can you kindly try again? Please make sure you're using Angular v9 from the start.

**Comment by mpern-sap** [comment] 2020-07-31 14:15
tried it again with a completely new project, same result

```
ng new demo --style=scss --routing=false --packageManager=yarn
cd demo
ng add @spartacus/schematics
ng g @spartacus/schematics:add-pwa
Cannot read property 'targets' of undefined
```

**Comment by znikola** [comment] 2020-07-31 14:17
I noticed that you are using `ng g @spartacus/schematics:add-pwa`. Can you try with `ng add @spartacus/schematics --pwa`?

**Comment by mpern-sap** [comment] 2020-07-31 14:18
please re-read the bug report 😄 

the point is exactly that `ng g @spartacus/schematics:add-pwa` doesn't work

**Comment by znikola** [comment] 2020-07-31 14:21
Yes, I understand. 
`ng add @spartacus/schematics --pwa` can be ran even after adding vanilla Spartacus (`ng add @spartacus/schematics`). 

And I just checked the docs, and I understand now why you tried running it like that :)
Created https://github.com/SAP/spartacus-docs/issues/716

**Comment by Xymmer** [comment] 2020-08-13 13:10
closing this one as the issue will be fixed in the doc through the ticket nik created

**Closed as completed by Xymmer** 2020-08-13 13:10 UTC
Labels: bug, schematics, from-community
