### ISSUE TITLE
suffixUrlMatcher doesn't allow fully override Category Page route

### ISSUE THREAD

**Issue by artem-zur** [SAP/spartacus#6266] opened 2020-01-27 16:14 UTC
ProductListingPageModule contains route by matcher which doesn't allow fully override Category Page routing.

## Environment Details

- Spartacus:  *-1.5.0

## Steps to Reproduce

1. Disable default Category route.
2. Add custom Category route with custom CategoryPageComponent and path = 'o/c/:categoryCode'.
3. Build application and start application.
4. Open custom route in browser.

## Observed Results

Spartacus route by matcher overrides custom route.

## Expected Results

We can override or disable default routing by matcher to provide self fully custom routing.

**Comment by Platonn** [comment] 2020-01-28 11:41
The suffix routes were introduced for backward compatibility with accelerators matching `**/c/:categoryCode` and by design placed rather shallow in our modules structure to opt out from them by dismantling and reassembling modules.

So for now, there is no way to disable special suffix routes by config. You need to to dismantle the `StorefrontModule` and `ProductListingPageModule`. Then reassemble without the route containing suffix url matcher.

Adding a special configuration can be considered it as a new feature. But it's debatable whether we should implement it or rather move routes out from StorefrontModule and place in other opt-in DefaultRoutesModule in some major version (it would be a breaking change).

**Comment by Platonn** [comment] 2020-04-24 07:56
Hi @artem-zur 
Configurable URL matchers were released in version `2.0.0-next.0` in 4a9c3487e2bae06d984517012af9694c89ce2269 and it helps fully owerwrite category page route. In this comment you can find how to do it: https://github.com/SAP/spartacus/issues/6583#issuecomment-590318708 . See points 7. and 8.
(docs on the official docs page will arrive soon)

**Closed** 2020-04-24 07:58 UTC
Labels: COULD, improvement
