### ISSUE TITLE
Unit address too large

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#10071] opened 2020-11-27 19:08 UTC
Occurred on:
- Safari - iOS 14.2 - iPhone 6s

To repro, got to the shipping address of a unit.  If there are no addresses, create one.
Issue:
 - The address is too large for the cell.

Expected results:
- The address text is displayed properly in the space it has.

Perhaps the address could be displayed in a less wide fashion so it can take less width in mobile view. (perhaps wrap with a new line for each address element.)

Screenshot: 
![Image from iOS (1)](https://user-images.githubusercontent.com/7065346/100478621-bf35f700-30b9-11eb-8e1c-d8896c38105a.png)

**Comment by Matejk00** [comment] 2020-11-30 14:12
Duplicate of #10045?

**Closed as completed** 2020-12-03 17:24 UTC
Labels: bug, styling, b2b-mycompany
