### ISSUE TITLE
[ccv2 dependency] Bug: SSR crashes with a '%2F' slash ('/') in the URL

### ISSUE THREAD

**Issue by sebastianfdez** [SAP/spartacus#12082] opened 2021-04-22 09:56 UTC
**Describe the bug**

Using SSR, the webpage can't be reloaded when the slash '/' (encoded '%2F' ) is present in the URL

**To Reproduce**
1. Go to: https://eshop.ntn-snr.com/en/
2. Search '100/' in the search bar
3. Click in 'show all results' inside the autocomplete
4.  Page will navigate to: 

https://eshop.ntn-snr.com/en/search/100%2F?tabNum=0&searchQueryContext=DEFAULT&matchType=CONTAINS

Notice that the searched value ('100/') in the URL is encoded ('100%2F')

5. See error:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/17834635/115694297-0373ad80-a361-11eb-91f1-7fa2b720fd6d.gif)

![Capture d’écran 2021-04-22 à 11 34 33](https://user-images.githubusercontent.com/17834635/115694336-0c647f00-a361-11eb-892d-ace2a74c57fe.png)

Doing the same steps but without a '/' the page does not crash.

**Expected behavior**
Page should behave like the demo page (not in SSR): 

https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/search/100%2F

You can reload and page does not crashes

![image](https://user-images.githubusercontent.com/17834635/115694762-75e48d80-a361-11eb-9349-97f0dd26f6fb.png)

**Tell us the version of Spartacus**
- Library version:  2.1

**Comment by giancorderoortiz** [comment] 2021-06-08 12:23
Possible duplicate of https://github.com/SAP/spartacus/issues/10540.
Please try workaround: #10541

**Comment by giancorderoortiz** [comment] 2021-06-11 21:52
Unable to reproduce with localhost in ssr mode, nor ccv2 (ssr mode). 
![Screen Shot 2021-06-11 at 5 51 52 PM](https://user-images.githubusercontent.com/46171897/121752266-c5337880-cadd-11eb-8bcf-c7a03e0f4a65.png)
![Screen Shot 2021-06-11 at 5 52 08 PM](https://user-images.githubusercontent.com/46171897/121752271-c5cc0f00-cadd-11eb-8809-3a48c9f30693.png)

**Comment by franckbattu** [comment] 2021-07-15 17:26
Hi. I work with @sebastianfdez who created this issue report.

I was able to reproduce this bug with your demo site:
1. Go on https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/ (apparently deployed in SSR mode)
2. Search "5/" for example and press Enter to see products results page. In this case, the page works.
3. Still on this products results page, press F5 to reload. The page crashs with a 404 error.

Furthermore, if I try to access directly on https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/search/5%2F, it won't work.

**Comment by giancorderoortiz** [comment] 2021-07-15 17:43
@LTiger14, @hackergil able to reproduce with 4.0 RC0.

**Comment by giancorderoortiz** [comment] 2021-07-19 15:50
Waiting for review by @dunqan to decide whether to fix for 4.0 or not.

**Comment by franckbattu** [comment] 2021-09-02 07:37
Any news?

**Comment by Xymmer** [comment] 2021-09-02 14:35
investigate if we can fix this, and also check if this is a bug in csr as well
we'll aim to add fix for 4.2

**Comment by LTiger14** [comment] 2021-09-07 19:17
MTD-22711 opened.

**Closed as completed** 2021-11-25 21:36 UTC
Labels: bug, SSR, backend-dependency, Major, model-t-dependency, fixed-with-backed-update
