### ISSUE TITLE
SmartEdit is not refreshing Spartacus page after a change (1905.13, 1.4.1)

### ISSUE THREAD

**Issue by rmontesinosg** [SAP/spartacus#8109] opened 2020-07-02 18:48 UTC
**Steps to reproduce:**

1. Open smartEdit, login with a user with all the CRUD permissions needed.
2. Open an existing page and edit it. Like edit an existing paragraph or add a new one.
3. After the action in step 2, the preview section is not refreshing the page with those changes.

**Expected:** The components changed on page get the changes directly, without a browser reload.

I see another issue related (https://github.com/SAP/spartacus/issues/2553#event-2360285062) closed before, could you please review again.

Hybris Commerce version: 1905.13 CXCOMM and Spartacus version: 1.4.1

**Comment by Xymmer** [comment] 2020-07-07 21:29
tested with latest 2.0 and 2005, cannot repro. 
Tried with 1.4.latest and 2005, cannot repro.
Might be something fixed in 2005 since 1905.

**Comment by Xymmer** [comment] 2020-07-08 15:29
using 1905.15 and Spartacus 1.4.3, all out of the box, we don't see this issue.
@rmontesinosg could you contact me directly and provide more steps/info or a video
maybe check also cache control headers (see https://sap.github.io/spartacus-docs/cors/#page-title)
ultimately best to ask for help in community support chat as it seems it might be specific to your implementation

**Comment by Xymmer** [comment] 2020-07-08 17:39
was able to reproduce when dragging paragraph component into a slot, with 1905.15 and 1.4.3
but isn't a problem in 2.0 with 1905.15.
so it was fixed along the way, trying to find out with what.

**Comment by rmontesinosg** [comment] 2020-07-14 13:21
Hi, good to know you were able to reproduce the issue with 1.4.1 version. Is there any solution/workaround for it?.
Thanks!

**Comment by Xymmer** [comment] 2020-08-25 13:55
Hi @rmontesinosg, no updates yet, sorry for delay in replying

**Comment by Xymmer** [comment] 2020-08-25 14:01
Hi @rmontesinosg so the minute I wrote that, I got word that this issue wasn't an issue in Spartacus, but an issue with caching in OCC.  Spartacus get cmsTicketId, and then appends it to all cms requests. For further support, best to created a support ticket.

**Closed as completed by Xymmer** 2020-08-25 14:01 UTC
Labels: bug, smartedit

**Comment by rmontesinosg** [comment] 2020-08-25 14:52
Yes, you're right. Thanks for the support!!!
