### ISSUE TITLE
Broken e2e regression/early-login.e2e-spec.ts

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9770] opened 2020-11-13 10:15 UTC
`regression/early-login.e2e-spec.ts` fails in `spartacus-regression-tests-2005` since run 3​99 (up to run 410).
Please note that run 398 had some changes but was aborted, so those changes could also affect failing 399.

**Comment by kacperknapik** [comment] 2020-11-13 10:30
Duplicate of https://github.com/SAP/spartacus/issues/9758

**Closed as completed** 2020-11-13 10:30 UTC
Labels: e2e-tests
