### ISSUE TITLE
B2B myco: sign in a user admin a, sign out, sign in as different user, units list sometimes doesn't load

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#10031] opened 2020-11-27 01:59 UTC
using RC1 on ccv2 for browser testing

1. Log in as an admin
2. Display units, works fine
3. Log out
4. Log in as another admin
5. Display units
... the gray bars appear and units don't display
![image](https://user-images.githubusercontent.com/4998145/100402425-34f28200-302a-11eb-992a-33c0ef5121b8.png)

**Comment by Pucek9** [comment] 2021-01-08 16:41
Cannot reproduce. It seems as already fixed by #9790

**Closed as completed by Pucek9** 2021-01-08 16:41 UTC
Labels: bug, my-company/org-units, b2b-auth, b2b-mycompany
