### ISSUE TITLE
2011 dev-server for E2E Testing

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9371] opened 2020-10-15 21:22 UTC
Deploy 2011 dev server for e2e tests. 
Use azure dev4.

**Comment by giancorderoortiz** [comment] 2020-10-19 12:38
Dev4 setup with 2011 snapshot. 
Swagger: 
https://electronics.spartacus-dev4.eastus.cloudapp.azure.com:9002/occ/v2/swagger-ui.html

**Comment by giancorderoortiz** [comment] 2020-10-19 12:38
Vanilla b2c: http://spartacus-dev4.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/

**Comment by giancorderoortiz** [comment] 2020-10-19 12:39
Deployed 2011.0.201014014 CS snapshot

**Comment by saad-mo** [comment] 2020-10-21 15:33
how to do QA?

**Comment by giancorderoortiz** [comment] 2020-10-22 15:56
Using localhost, run smoke, regression, mobile and all other applicable e2e tests. 
If asm tests fail, please change password to default ccv2 password. 
Please record runs and add dashboard links to this ticket. 
Compare to 2005 and highlight test failures. 
Subsequently, let's discuss which ones actually require fixing. 

The ultimate goal is to have e2e tests running against 2011.

**Comment by giancorderoortiz** [comment] 2020-10-22 15:57
@saad-mo, @hackergil can provide you with details how to record tests.

**Comment by hackergil** [comment] 2020-10-23 12:56
@giancorderoortiz  https://docs.cypress.io/faq/questions/dashboard-faq.html#How-do-I-record-my-tests

**Comment by bgambocjaviniar** [comment] 2020-10-26 17:21
added jenkins job to do the test last Friday
- will analyse tomorrow or later today
- builds contains recorded tests at the bottom of the of the console output

b2c 2011 https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/test-spartacus-regression-tests-2011-b2c/ 
b2b 2011 https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/test-spartacus-regression-tests-2011-b2b/


^ for testing purposes and will be deleted once done or kept if we need it

*Note: Expected version ">= 10.14.2". Got "10.14.1" `error` for b2b 2011 job is similar to what happens for our original b2b job. Will be running this manually as this is a small collection

**Comment by bgambocjaviniar** [comment] 2020-10-29 05:48
Findings:

Branch: `feature/test-e2e-2011`
env: `dev4-azure` 

Looks like the dev4 server for 2011 is not configured properly as most of the failures is related to failing to checkout because the delivery mode is not delivery-standard-net.

THREE things main things for the failures in #build 3, 4, 5 (pre-sessionmanagement feature merge)
1)  delivery mode problem where e2e is looking for delivery-standard-net, but most likely it's configured to something else in this server
2) total price being wrong - most likely because of 1)
3) my-interest and consignment missing e2e test data as their not functioning in their last step


Closing as we can verify and test 2011 using the job in the comments above
- each build in the job will have a cypress dashboard at the end of it's summary

**Comment by giancorderoortiz** [comment] 2020-10-29 09:16
2011 dev server setup the same way as all others. 
Re-opening so I can investigate.

**Closed as completed** 2020-10-29 12:58 UTC
Labels: team/gladiators, infrastructure

**Comment by giancorderoortiz** [comment] 2020-10-29 14:43
https://github.com/SAP/spartacus/issues/9576
