### ISSUE TITLE
Mock icon loader in our tests

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#8548] opened 2020-08-11 14:26 UTC
The following exeption appears 
**this.iconLoader.getFlipDirection is not a function** after develop was merged into our epic.

**Comment by Xymmer** [comment] 2020-08-17 13:52
Possibly @tobi-or-not-tobi a fix was added somewhere?

**Comment by tobi-or-not-tobi** [comment] 2020-08-17 14:07
Duplicate of #8543

**Closed as completed by tobi-or-not-tobi** 2020-08-17 14:07 UTC
Labels: vc
