### ISSUE TITLE
NPM CI throwing error due to fsevents

### ISSUE THREAD

**Issue by PascalAOMS** [SAP/spartacus#7297] opened 2020-04-20 08:22 UTC
## Environment Details
- Spartacus:  next.4
- Browser: Chrome
- OS: Windows 10
- Angular: 9.0.1

## Steps to Reproduce
- Install version next.4
- Run `npm ci` (locally or in actual CI environment)

## Observed Results
When running `npm ci` locally or with Jenkins, this error is thrown:
```
fsevents@1.2.12 install
> node-gyp rebuild
...
File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1791, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1744, in _DictsToFolders
    for folder, contents in bucket.items():
AttributeError: 'MSVSProject' object has no attribute 'items' 
```

On that topic I was able to find this ticket:
https://github.com/npm/cli/issues/558

The Angular version was installed with next.2 as well and was working normally then.

## Expected Results
Installation should go through.

## Offer to Fix
No

**Comment by Xymmer** [comment] 2020-04-20 13:13
spike the issue, verify if really a must for 2.0.
set to stretch or future issue if not, otherwise we fix for 2.0.
consult with Kris to verify.

**Comment by Xymmer** [comment] 2020-04-20 13:14
@PascalAOMS could you upgrade Angular to latest (9.1.x).

**Comment by PascalAOMS** [comment] 2020-04-20 13:27
I updated to the latest Angular version.
Jenkins still aborts when running `npm install` or `npm ci`.

**Comment by kacperknapik** [comment] 2020-05-05 13:54
I cannot reproduce this error. Works fine for me, on Win10

**Comment by Xymmer** [comment] 2020-05-05 23:12
@PascalAOMS any other info you can give us?

**Comment by Xymmer** [comment] 2020-06-27 16:29
closing as we didn't hear back. if we get new news, we'll reopen or create new bug

**Closed as completed by Xymmer** 2020-06-27 16:29 UTC
Labels: bug, team/gladiators

**Comment by PascalAOMS** [comment] 2020-07-16 14:56
Sorry for the delay.
In the end the issue was somewhere else.

Thank you for the responses!
