### ISSUE TITLE
Migration failed: Option "name" is required.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#7545] opened 2020-05-08 21:29 UTC
When I ran `ng update @spartacus/schematics --next` on the bootcamp repo, I get the error `Migration failed: Option "name" is required.`

<img width="872" alt="Screen Shot 2020-05-08 at 5 24 37 PM" src="https://user-images.githubusercontent.com/7065346/81450906-5b65d400-9151-11ea-836f-8e47971f838d.png">

The content of the log file is:

```
[error] Error: Option "name" is required.
    at SchematicImpl.<anonymous> ([...]/spartacus-bootcamp-2.0/node_modules/@angular/localize/schematics/ng-add/index.js:101:35)
    at step ([...]/spartacus-bootcamp-2.0/node_modules/tslib/tslib.js:139:27)
    at Object.next ([...]/spartacus-bootcamp-2.0/node_modules/tslib/tslib.js:120:57)
    at [...]/spartacus-bootcamp-2.0/node_modules/tslib/tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter ([...]/spartacus-bootcamp-2.0/node_modules/tslib/tslib.js:109:16)
    at [...]/spartacus-bootcamp-2.0/node_modules/@angular/localize/schematics/ng-add/index.js:95:49
    at MergeMapSubscriber.pipe.operators_1.mergeMap.inputTree [as project] (/private/var/folders/w9/cqtd72355l7298y2njwq061h0000gn/T/angular-cli-packages-UvWf9M/node_modules/@angular-devkit/schematics/src/rules/call.js:74:24)
    at MergeMapSubscriber._tryNext (/private/var/folders/w9/cqtd72355l7298y2njwq061h0000gn/T/angular-cli-packages-UvWf9M/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/private/var/folders/w9/cqtd72355l7298y2njwq061h0000gn/T/angular-cli-packages-UvWf9M/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/private/var/folders/w9/cqtd72355l7298y2njwq061h0000gn/T/angular-cli-packages-UvWf9M/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/private/var/folders/w9/cqtd72355l7298y2njwq061h0000gn/T/angular-cli-packages-UvWf9M/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/private/var/folders/w9/cqtd72355l7298y2njwq061h0000gn/T/angular-cli-packages-UvWf9M/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/private/var/folders/w9/cqtd72355l7298y2njwq061h0000gn/T/angular-cli-packages-UvWf9M/node_modules/rxjs/internal/Observable.js:30:22)
    at MergeMapOperator.call (/private/var/folders/w9/cqtd72355l7298y2njwq061h0000gn/T/angular-cli-packages-UvWf9M/node_modules/rxjs/internal/operators/mergeMap.js:39:23)
    at Observable.subscribe (/private/var/folders/w9/cqtd72355l7298y2njwq061h0000gn/T/angular-cli-packages-UvWf9M/node_modules/rxjs/internal/Observable.js:25:31)


```

**Comment by znikola** [comment] 2020-05-11 08:01
Dupe of https://github.com/SAP/spartacus/issues/7542, closing

**Closed as completed by znikola** 2020-05-11 08:01 UTC
Labels: schematics-migration
