### ISSUE TITLE
Unknown error when creating a new user

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#10170] opened 2020-12-01 20:22 UTC
**Describe the bug**
An unknown user when creating in my company. It should be noted that this error is a bit flaky and does not happen consistently and usually happens on the first attempt to create a user. The process works if you refresh the page. 

**Tell us the version of Spartacus**
- Library version: 3.0-RC1. 
- Discovered while testing for  #10012

**To Reproduce**
1. My company home > User > ADD button
2. Fill out the form and tab SAVE
3. Observe the error 

**Expected behavior**
Should create a user without any error or show an appropriate error message.

**Screenshots**
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-11-30 at 14 52 27](https://user-images.githubusercontent.com/15215400/100791718-40a1c800-33df-11eb-9742-5e8841567d9c.png)

**Desktop (please complete the following information):**
 - OS: iPad Mini using xcode simulator 
 - Browser: Safari
 - Version: Lastest 

**Additional context**
This could be a result of a slow connection or server response. I had noticed that the response time was a bit slow in the overall responsiveness of the UI.

**Comment by Xymmer** [comment] 2020-12-02 01:10
dupe of known issue where we don't get error messages
in this case, the email suffix .approve is not an official suffix like .com

**Closed as completed by Xymmer** 2020-12-02 01:10 UTC
Labels: bug
