### ISSUE TITLE
Failing E2E: tabbing-order

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#7020] opened 2020-03-24 03:17 UTC
failing constantly since the refactoring on some parts of accessibility

more info: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/909/consoleText

**Comment by kacperknapik** [comment] 2020-04-20 14:31
Duplicate of #6758

**Closed as completed by kacperknapik** 2020-04-20 14:31 UTC
Labels: e2e-tests
