### ISSUE TITLE
Not-found API appears for 1st time guest-checkout while moving from cart to checkout

### ISSUE THREAD

**Issue by srikanta72** [SAP/spartacus#11646] opened 2021-03-24 15:17 UTC
Hi team, 
We see an issue when a customer moving from Cart page to Checkout where "not-found" returned from backend as part of the page API response. However the next consecutive page API response are correct where UI is appearing fine without any issue. 

In our site we are using Analytics based on page API response where the analytics data appearing as error page info before moving to next page. 
Hence the issue is a blocker for Analytics in our website. 

The scenario appears to be happening for first time guest checkout in same session. 
I checked in the Spartacus demo site the issue is available. 

Attaching the screenshots for reference. 

Kindly look into the issue and let us know if we can have an alternative fix for this.

Steps: 
Open the URL : Spartacus demo site 
Add an item to cart 
Go to cart page >> Go to inspect >> Network tab >> clear the list (To see the next Urls only)
Then proceed to checkout 
It will ask for Login /Guest Checkout 
Do a guest Checkout ( in case of demo site I did a login as guest checkout is not available)
Then it will land on next page. 
Go Network tab >> Check the pages API requests where a page api return not-found.

I have attached screenshot for spartacus demo site
![Screenshot (435)](https://user-images.githubusercontent.com/25590140/112335150-fe7bf980-8ce1-11eb-91a9-59532e8ff504.png)

**Comment by LTiger14** [comment] 2021-06-11 14:41
Could not reproduce on https://spartacus-training.eastus.cloudapp.azure.com/electronics-spa/en/USD.
or develop with dev backend
or 3.1 with dev backend
or 3.0

Could reproduce in 2.1

The issue is present in 2.x but fixed in 3.x.

Training server (login):
![Screen Shot 2021-06-11 at 10 38 46 AM](https://user-images.githubusercontent.com/10605724/121704115-736cfd00-caa1-11eb-8e91-dad1382cb087.png)

**Comment by LTiger14** [comment] 2021-06-11 19:11
Closing as this is fixed in 3.x.

Please contact us or reopen if this is a blocker.

**Closed as completed by LTiger14** 2021-06-11 19:11 UTC
Labels: bug, Major
