### ISSUE TITLE
Sorting Dropdown cannot be opened

### ISSUE THREAD

**Issue by PascalAOMS** [SAP/spartacus#7009] opened 2020-03-23 13:17 UTC
## Environment Details

- Spartacus:  2.0.0.next.1
- Browser: current Chrome
- OS: Windows 10

## Steps to Reproduce
1. Run Spartacus locally.
2. Open https://localhost:4200/electronics-spa/en/USD/Open-Catalogue/Cameras/CameraAccessories-%2526-Supplies/CameraLenses/c/588
3. Click the sort button which says "Relevance".

## Observed Results
Clicking the dropdown throws two errors which read:
```
core.js:5871
TypeError: Cannot read property 'nativeElement' of undefined
    at NgDropdownPanelComponent.ngOnInit (ng-select.js:2102)
```

```
zone-evergreen.js:659 
Unhandled Promise rejection: 
Cannot read property 'clientHeight' of undefined ; 
Zone: <root> ;
Task: Promise.then ;
Value: TypeError: Cannot read property 'clientHeight' of undefined
```

## Expected Results
The dropdown menu opens.

## Offer to Fix
No.

## Additional Information
It's an untampered Spartacus installation.

**Comment by KateChuen** [comment] 2020-04-07 13:38
Repro first.

**Comment by qjimmy** [comment] 2020-04-08 21:45
Couldn't repro

- tested on ff and chrome
- MacOS

**Comment by KateChuen** [comment] 2020-04-09 13:39
@PascalAOMS Is this still happening? And could you also verify on MAC or maybe it's just a WINDOWS issue please? Can you tell us the specific version of chrome you're using as well? If you could also try on Windows Firefox and Edge, so we can pinpoint where the problem is.

**Comment by eljoujat** [comment] 2020-04-12 10:34
Hi ,

I just reproduced the same issue :

- MacOs Mojave (version 10.14.6) 
- Chrome Version 80.0.3987.163 

I thins it's a compatibility issue with Rxjs and angular see [https://stackoverflow.com/questions/50316141/ng-select-in-angular5-issue-error-typeerror-object-is-not-a-function-at](https://stackoverflow.com/questions/50316141/ng-select-in-angular5-issue-error-typeerror-object-is-not-a-function-at)

The  given solution worked for me : `npm i -s @ng-select/ng-select@latest rxjs-compat`

**Comment by niveditapdixit** [comment] 2020-04-15 07:36
Thanks @eljoujat . Had the same issue, resolved it by executing  `npm i -s @ng-select/ng-select@latest rxjs-compat`

**Comment by Xymmer** [comment] 2020-04-25 18:57
@ our dev, triage and determine if this is still a bug to fix, or close if not

**Comment by kacperknapik** [comment] 2020-05-06 09:43
Cannot reproduce

**Comment by Xymmer** [comment] 2020-05-06 21:38
closing as it seems to be a dependency issue, please contact @kacperknapik if it persists

**Closed as completed** 2020-05-07 09:09 UTC
Labels: bug, team/obelix, from-community
