### ISSUE TITLE
SonarC. Reliability Rating. Use <em> instead of <i>

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10278] opened 2020-12-08 21:18 UTC
This issue affects our overall Reliability Rating in Sonar Cloud.
Visible to CX.

Reliability Rating:
B

Link: 
[icon.component.html](https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=reliability_rating&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects%2Fstorefrontlib%2Fsrc%2Fcms-components%2Fmisc%2Ficon%2Ficon.component.html)

File: 
projects/storefrontlib/src/cms-components/misc/icon/icon.component.html

Issue: 
Replace this <i> tag by <em>.

**Comment by giancorderoortiz** [comment] 2020-12-08 21:18
![Screen Shot 2020-12-08 at 4 15 16 PM](https://user-images.githubusercontent.com/46171897/101542646-1026d480-3971-11eb-985f-7fb4a3ae4a22.png)

**Comment by Xymmer** [comment] 2020-12-15 16:32
dupe of #8827
also we want to disable that rule

**Closed as completed by Xymmer** 2020-12-15 16:32 UTC
Labels: bug, sonar-violations
