### ISSUE TITLE
Back to list approval button wrong behavior

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9334] opened 2020-10-14 16:44 UTC
**Describe the bug**
1. When submitting approval, the back button disappears. Refreshing the page shows a back button.
2. When looking at an order that has been approved or rejected on the approver dashboard, the back to list button redirects home.

**To Reproduce**
1. As an Approver approve or reject an order
2. *notice the button disappear*
3. *refresh*
4. The button is visible
5. Clicking the button redirects to home page

**Expected behavior**
The button is always visible and returns to list page.

**Screenshots**
1. Order not approved
<img width="369" alt="image" src="https://user-images.githubusercontent.com/10605724/96019444-8a782400-0e1a-11eb-8dd4-52b94059392d.png">
2. Approved or rejected
<img width="378" alt="image" src="https://user-images.githubusercontent.com/10605724/96019451-8d731480-0e1a-11eb-8917-5e8f9af7da17.png">
3. Refresh page
<img width="376" alt="image" src="https://user-images.githubusercontent.com/10605724/96019459-8fd56e80-0e1a-11eb-97c4-4792e9fb4023.png">
4. Link href
<img width="310" alt="image" src="https://user-images.githubusercontent.com/10605724/96019466-9237c880-0e1a-11eb-9c24-fbc6c936e5e0.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Firefox 82
- Version latest develop 3.0 next.4? with dev0

**Comment by plabadie** [comment] 2020-10-14 19:29
Duplicate of  https://github.com/SAP/spartacus/issues/9122

**Closed as completed** 2020-10-15 01:35 UTC
Labels: bug, team/gladiators, my-company/approval-dashboard
