### ISSUE TITLE
Sign In / Register textlink in header is one single continuous link

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#2243] opened 2019-04-30 18:16 UTC
Description:  On the header, the Sign In / Register textlink is a single link that goes to the sign in page. If a user wishes to ‘Register’ they should click on the Register link only and be taken directly to the ‘Register’ Page, not having to pass to the Sign In page and click Register a second time.

How to duplicate: On the header, click ‘register.’ Then on the homepage click "Sign in". Notice that they both go to the same place.

<img width="420" alt="Screen Shot 2019-04-12 at 11 23 02 AM" src="https://user-images.githubusercontent.com/44620139/56983779-7d964080-6b52-11e9-9551-c53f17a8ffc3.png">

**Comment by vekterdude** [comment] 2019-04-30 18:17
Manu will provide guidelines for the exact way this should look. The photo provided here suggests that it is one single link.

**Comment by Xymmer** [comment] 2019-05-07 13:18
this is a bigger code change than first appears, i'm moving to after 1.0

**Comment by qjimmy** [comment] 2020-06-29 14:33
@Xymmer can we close this? Could not reproduce using 2005 with latest develop

**Closed** 2021-06-03 14:32 UTC
Labels: header, improvement, login, outdated-and-closed-from-2019, registration
