### ISSUE TITLE
CCv2 build and deploy with Spartacus 2.0

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#7993] opened 2020-06-17 11:52 UTC
Customers who try to run Spartacus 2 based Applications to ccv2 face build and deploy issues. Investigations are in progress, but we're getting already some clues about the issue. 

The fundamental issue is related to a changing file layout from angular 8 to 9. Spartacus 2 moved to Angular 9, and with this, customers would likely receive the standard angular 9 based file layout after building. 

The angular 8 based file layout contains a dist folder with all the application build files in a subfolder. The SSR entry file (`server.js`) has been stored in the dist folder. 
(note: the `main.js` in the test-app-server is an intermediate build file and not used in ccv2 build/deploy). 

![image](https://user-images.githubusercontent.com/4745807/84893901-4b220c80-b0a0-11ea-8c93-e4fec23a8668.png)

The difference in the angular 9 based applications is that the client rendering and server rendering are separated in two named folders. 

![image](https://user-images.githubusercontent.com/4745807/84893917-5117ed80-b0a0-11ea-85c1-a4a86252a77d.png)

A couple of important changes: 
- The `server.ts` file has moved to the nested server folder
- The `index.html` has moved to the nested browser folder

The different file layout is quite likely the root cause.

## To be verified
- It seems that the ccv2 build/deploy is copying the `index.html` to a location. Given that the underlying file structured changed, we seem to have a misalignment. 
- ~We don't know if~ this is also causing issue for non-SSR deployments
- The solution should be backwards compatible, ~moreover we're not yet sure if recent changes affect the 1.5 releases~. 
- ~a quick code analysis of the ccv2 build process shows that the occ placeholder meta tag does not get replaced correctly~. 

## Potential Solution Directions
- change the angular build process to adapt the current expected file layout (this could be quick win for current customers)
- ~introduce a schematics to fit the ccv2 general file layout~
- improve ccv2 to adapt both ng8 and ng9 file layout
- add properties to the manifest.json so that customers are more in control
- ~consider using package.json as an configurable script to start the application~

**Comment by dunqan** [comment] 2020-06-17 15:05
As initially discussed with ccv2 team members, we would like to make `manifest.json` more configurable, to accommodate more specific cases (and keep backward compatibility with current solutions). 
Also, for now, the best approach is to adapt Angular build process to match the expected layout, which means:

- change of outputPaths in `angular.json`
  - `"outputPath": "dist/app-name/browser"`, to `"outputPath": "dist/app-name",`
  - `"outputPath": "dist/app-name/server"`, tp `"outputPath": "dist/app-name-server",`
- change in `server,ts`:  
    - `const distFolder = join(process.cwd(), 'dist/app-name/browser');` to
  `const distFolder = join(process.cwd(), 'dist/app-name');`

**Comment by ankitbansalnagarro** [comment] 2020-06-18 08:25
Thanks dunqan for the help, it seems to resolve the issue in CCV2.

**Comment by tobi-or-not-tobi** [comment] 2020-06-18 11:27
The update we're planning in ccv2 is driven by https://cxjira.sap.com/browse/MTD-13979.

**Comment by Xymmer** [comment] 2020-07-08 18:51
retest after we get ccv2 fixed, and also don't forget to update the release notes to remove mention of this issue and its workaround.

**Comment by ankitbansalnagarro** [comment] 2020-07-09 01:14
> 
> 
> retest after we get ccv2 fixed, and also don't forget to update the release notes to remove mention of this issue and its workaround.

when is the CCV2 fix planned? I'm unable to see JIRA

**Comment by artem-zur** [comment] 2020-07-10 14:15
> As initially discussed with ccv2 team members, we would like to make `manifest.json` more configurable, to accommodate more specific cases (and keep backward compatibility with current solutions).
> Also, for now, the best approach is to adapt Angular build process to match the expected layout, which means:
> 
> * change of outputPaths in `angular.json`
>   
>   * `"outputPath": "dist/app-name/browser"`, to `"outputPath": "dist/app-name",`
>   * `"outputPath": "dist/app-name/server"`, tp `"outputPath": "dist/app-name-server",`
> * change in `server,ts`:
>   
>   * `const distFolder = join(process.cwd(), 'dist/app-name/browser');` to
>     `const distFolder = join(process.cwd(), 'dist/app-name');`

Hi guys!
Unfortunately this workaround doesn’t fix Spartacus 2.0 build issue to CCv2. Or maybe I loose something ?

I’m still getting the error during scripts running:

```
* What went wrong:
Execution failed for task ':createJsAppsSSRImageStructure'.
> file /opt/workspace/build/customer-project/js-storefront/spartacusstore/dist/server.js doesn't exist!
```

And it’s fully right behaviour even based on official docs https://help.sap.com/viewer/b2f400d4c0414461a4bb7e115dccd779/SHIP/en-US/cd5b94c25a68456ba5840f942f33f68b.html

Especially:
> Commerce Cloud uses dist/server.js to start the SSR application. If that javascript file isn’t found, the build fails.

Or maybe we just don’t have any working solutions for now ?

P.S. I have sent our CCv2 build logs file to @dunqan.

**Comment by arelsirin** [comment] 2020-07-10 19:42
> As initially discussed with ccv2 team members, we would like to make `manifest.json` more configurable, to accommodate more specific cases (and keep backward compatibility with current solutions).
> Also, for now, the best approach is to adapt Angular build process to match the expected layout, which means:
> 
> * change of outputPaths in `angular.json`
>   
>   * `"outputPath": "dist/app-name/browser"`, to `"outputPath": "dist/app-name",`
>   * `"outputPath": "dist/app-name/server"`, tp `"outputPath": "dist/app-name-server",`
> * change in `server,ts`:
>   
>   * `const distFolder = join(process.cwd(), 'dist/app-name/browser');` to
>     `const distFolder = join(process.cwd(), 'dist/app-name');`

Hi! what if additionally, we copy the `app-name/dist/server/main.js` file to `app-name/dist/server.js`, and change the `serve:ssr` task in the `package.json` file to execute `node app-name/dist/server.js`, would that make it work (while the ccv2 fix is implemented)?

**Comment by dunqan** [comment] 2020-07-15 11:56
> Hi! what if additionally, we copy the `app-name/dist/server/main.js` file to `app-name/dist/server.js`, and change the `serve:ssr` task in the `package.json` file to execute `node app-name/dist/server.js`, would that make it work (while the ccv2 fix is implemented)?

Yes @arelsirin , it should work and it's now a recommended workaround as fixing it in CCV2 might be delayed because of various reasons. 

One way to make it automated, is for example to adding ` && mv dist/app-folder-server/main.js dist/server.js || move dist\\app-folder-server\\main.js dist\\server.js",` to `build:ssr` command in `package.json`.

**Comment by Xymmer** [comment] 2020-08-11 12:06
hey all, the workaround for now is documented here: https://sap.github.io/spartacus-docs/ssr-ccv2-issue-spartacus-version-2/

We're working on updating the CCv2 release process so that this workaround is not required, for 2.x libraries. We'll announce something when it's released.

**Comment by Xymmer** [comment] 2020-10-27 15:35
closing as i have it working and we hvae workaround documented, new tickets for continuing to update for newer versions and documenting

**Comment by janwidmer** [comment] 2020-11-05 12:02
Hey @Xymmer is the new issue you mentioned already created (just so that we can keep track of it..)?

**Comment by janwidmer** [comment] 2020-11-24 11:46
@Xymmer any update on this?

**Comment by mpern** [comment] 2020-12-09 10:44
I think the follow up is #10205

**Comment by tobi-or-not-tobi** [comment] 2021-01-21 20:41
Reopening as the latest changes have only partially fix the problem. @LTiger14 could you provide the updated workaround here with a relation to the related ccv2 application definition?

**Comment by LTiger14** [comment] 2021-01-21 20:57
After the latest update to CCv2 it's possible to provide the path to your server output file `main.js`.

The old format of `manifest.json` is still supported.

The  new format is as follows: (the most up to date information can be found here https://help.sap.com/viewer/b2f400d4c0414461a4bb7e115dccd779/v2011/en-US/cd5b94c25a68456ba5840f942f33f68b.html)
```
{
  "applications": [
      {
          "name": "<your storefrontapp name>",
          "path": "<your storefrontapp path>",
          "ssr": {
                "enabled": true,
                "path": "dist/<your storefrontapp name>/server/main.js"
          }
      }
  ]
```
If you use the following format you still need to do the following in your Spartacus storefront:

1. In your `angular.json` change your build output path like this:

> - `dist/app-name/browser` to `dist/app-name`

2. In your `server.ts` change

> - `const distFolder = join(process.cwd(), 'dist/app-name/browser')` to `const distFolder = join(process.cwd(), 'dist/app-name')`

**Comment by mpern** [comment] 2021-01-22 09:13
FYI, `ssr.path` the manifest snippet above doesn't match the default values when building a Spartacus storefront from libraries.
the correct snippet is:
```json
{
    "applications": [{
        "name": "<app name>",
        "path": "<app path>",
        "ssr": {
            "enabled": true,
            "path": "dist/<app name>/server/main.js"
        }
    }]
}
```
In combination with the two manual changes mentioned by @LTiger14 you have working SSR setup on CCv2 for Spartacus 3.0.1 (just tested it)

**Comment by mpern** [comment] 2021-04-25 13:11
All the problems described above were fixed with recent changes to the CCv2 deployment logic.

The *only* thing you have to do now is configure the CSR and SSR paths in your `manifest.json`.

```json
{
    "applications": [
        {
            "name": "spartacusstore",
            "path": "spartacusstore",
            "ssr": {
                "enabled": true,
                "path": "dist/spartacusstore/server/main.js"
            },
            "csr": {
                "webroot": "dist/spartacusstore/browser/"
            }
        }
    ],
    "nodeVersion": "12"
}
```

Details: 

- [Enabling Server-Side Rendering](https://help.sap.com/viewer/b2f400d4c0414461a4bb7e115dccd779/LATEST/en-US/cd5b94c25a68456ba5840f942f33f68b.html)
- [Setting Client-Side Rendering Web Root Path](https://help.sap.com/viewer/b2f400d4c0414461a4bb7e115dccd779/LATEST/en-US/0d54fc7faaa44b14b15b164cb1f3f2b6.html)

**Comment by janwidmer** [comment] 2021-04-26 07:28
@mpern are you sure, that the csr part can be nested in a `/browser` subfolder? Because here (https://sap.github.io/spartacus-docs/ssr-ccv2-issue-spartacus-version-2/#workaround-for-the-new-manifest-format) it says, that the CSR app needs to be in the root app folder..

**Comment by mpern** [comment] 2021-04-26 11:39
I double-checked while updating [SAP-samples/cloud-commerce-sample-setup / 2011-spartacus][sample] to spartacus@3.2.0

The workaround isn't necessary anymore. (tested on a non-public subscription)

[sample]: https://github.com/SAP-samples/cloud-commerce-sample-setup/tree/2011-spartacus

**Comment by janwidmer** [comment] 2021-05-03 08:09
@mpern I can confirm that it works now with the standard angular file structure as you have commented.

When closing this issue, the docs could also be adjusted here: https://sap.github.io/spartacus-docs/ssr-ccv2-issue-spartacus-version-2/#further-reading

**Comment by LTiger14** [comment] 2021-06-01 19:41
Closing as this is now fixed. Docs have been fixed, please see https://sap.github.io/spartacus-docs/ssr-ccv2-issue-spartacus-version-2/#resolving-the-issue

**Closed as completed by LTiger14** 2021-06-01 19:41 UTC
Labels: bug, SSR, ccv2

**Comment by Exotelis** [comment] 2022-03-25 08:28
Hey everyone,

in our project we want to use a prebuild application on the cloud. Unfortunately, the `dist/` we submit to the cloud is completly ignored. Currently, we build the following structure:

```
dist
|--<app-name>
   |--browser
      |-- index.html
   |--server
      |-- main.js
```
The manifest is structured as follows:
```
{
  "applications": [
    {
      "name": "<app-name>",
      "path": "<app-name>",
      "ssr": {
        "enabled": true,
        "path": "dist/<app-name>/server/main.js"
      },
      "csr": {
        "webroot": "dist/<app-name>/browser/"
      }
    }
  ],
  "nodeVersion": "12"
}
```

is the cloud expecting a different structure? We stumbled over a few documentations which are not very consistent in some points. Also, the only place where I could find some information about the prebuild is here: https://help.sap.com/viewer/b2f400d4c0414461a4bb7e115dccd779/v2105/en-US/63577f67a67347bf9f4765a5385ead33.html
On the help page the example expects the `index.html` not to be in the `browser` directory. However, the build on the cloud is working perfectly fine, but not the prebuild approach.

Cheers

**Comment by mueller-florian-rh** [comment] 2022-03-28 07:30
Hi @Exotelis! 

And how does the structure above dist folder look like?

According to your manifest.json it should be

`repository-root/js-storefront/<app-name>/dist`

**Comment by Exotelis** [comment] 2022-03-28 07:33
Hi @mueller-florian-rh 

`<project-root>/js-storefront/<app-name>/dist`
The `manifest.json` is placed in the js-storefront dir

Update: As pointed out, the usual build process works. The cloud does the `yarn install`, `yarn build:ssr` things. But to have more control over the build process we would like to prebuild and let the cloud use the already existing `dist` folder. I don't see any problem in out configuration. At least everything is according to the documentation.

**Comment by mueller-florian-rh** [comment] 2022-03-28 07:43
Hi @Exotelis :

The thing is, that using a prebuild application it should not run the build process at all. Instead you should see something in the logs like `Using pre built javascript application: <app-name>`

**Comment by Exotelis** [comment] 2022-03-28 07:52
Hey @mueller-florian-rh 

yep this is definitely not the case. That's why I'm asking if the cloud is expecting some other structure as documented - maybe the angular8- build structure or something like this.
