### ISSUE TITLE
Requesting a large amount of components at once from the CmsService is failing 

### ISSUE THREAD

**Issue by ZakTreister** [SAP/spartacus#13080] opened 2021-07-13 10:22 UTC
- Description:
In my project I have a very large navigation tree. Once the CategoryNavigationComponent/NavigationService try to retrieve the navigation-node-components, all the requests are sent to the CmsService at once.
The call to the backend then looks like this:
`/cms/components?fields=DEFAULT&currentPage=0&pageSize=713&componentIds=<huge_list_of_components> `
Which results in a server error:
Status Code: 431 Request Header Fields Too Large

- Library version: 3.4

- Screenshot:
![image](https://user-images.githubusercontent.com/43063428/125434911-5dda5587-2c60-455a-8697-caf5e9510b26.png)

 - OS: Windows
 - Browser: chrome

**Comment by giancorderoortiz** [comment] 2021-07-16 19:35
@WeizhengSap, @plabadie fyi. Please take a look. Is this in fact an issue?

**Comment by giancorderoortiz** [comment] 2021-07-19 15:40
Doesn't block 4.0. Will fix in 4.1 and backport to 3.4.

**Comment by WeizhengSap** [comment] 2021-07-19 17:06
If the number of components is too large, components can be retrieved page by page. In `OccCmsComponentAdapter`, there is function 
```
findComponentsByIds(
    ids: string[],
    pageContext: PageContext,
    fields = 'DEFAULT',
    currentPage = 0,
    pageSize = ids.length,
    sort?: string
  ): Observable<CmsComponent[]>
```

**Comment by WeizhengSap** [comment] 2021-07-19 17:07
What we can do in 4.1 is to create a facade service for it.

**Comment by LTiger14** [comment] 2021-07-26 20:06
Can be resolved by updating the `findComponentsByIds` to split the request in multiple parts. Talk to me about the implementation details.

**Comment by ZakTreister** [comment] 2021-07-26 20:22
@LTiger14 sure I overrode it easy. Question here is if it shouldn't be in the core code

**Comment by ZakTreister** [comment] 2021-07-26 20:25
@LTiger14 I already have some code it's not complicated

**Comment by Xymmer** [comment] 2021-09-02 14:31
There's a fix for ccv2 that makes header size larger. If still an issue we can add the improvement here.
Let's also create a new issue for perhaps using lazy loading to improve performance.

**Comment by neilhubertprice** [comment] 2021-11-17 10:05
@Xymmer I have another customer with the same issue.  The problem does not relate to header size, it relates to the maximum length of URL including querystring.  Currently this is implemented as a GET & when the main menu navigation node structure includes 100s of items (quite easily achieved) then the querystring gets very long because all component IDs within the main menu are included in a single call.

If you look at the cmsocc API, there is a POST version of the components call with comments that the GET version will potentially exceed maximum URL length if the list of components is too long - however that POST version is deprecated, so splitting the GET call into batches (as discussed earlier in the ticket) seems like the appropriate fix.  This should only need changes in OccCmsComponentAdapter

**Closed as completed** 2022-04-21 17:43 UTC
Labels: improvement, Major

**Comment by bgambocjaviniar** [comment] 2022-04-22 16:21
QA:

Context:
- Currently, we have the default cms components request set to `50`. Basically, if any requests contains more than 50 cms components, it will split the requests into 'chunks'. 
> For example, there is a request for 80 cms components. With this default value, it will split the 1 request into 2 requests. 1 request containing 50 of the cms components and the other request containing the remaining 30. Another example is if the requests contains 160 cms components, then it will break it down into 4 requests. 3 of the requests will request for 50 cms components, and the last one will request for 10 cms components.

QA steps: 
1. visit any spartacus route like `http://localhost:4200/electronics-spa/en/USD/product/1934796/powershot-a480`
2. open dev tools and choose the network tab. In the input box for 'filter', type components. Make sure the checkbox for 'Preserve log' is unchecked. You should be seeing 3 'distinct' requests. 1 request, which has 26 total count. Another one with a total count of 8, and the last one with a total count of 4. (recall our default split request is set to 50, so this shows that nothing affects the request as it was before)
3. change the default 'split' cms components by providing this config somewhere like in your `app.module.ts`
```
    provideConfig({
      componentsLoading: {
        pageSize: 20,
      },
    }),
```
4. EXPECTED results:  look at your dev tools after refreshing the page. You should now have 4 requests. The request with 26 total count has been split into 2. 1 request with 20, another one with 6. The other 2 being the same.

P.S change the values in pageSize to test the split of different requests. If you set the pageSize to 1, then the total requests will be 38. Instead of manually counting the number of requests sent, you can view the total number from the 'footer' as shown in the screenshot
![Screen Shot 2022-04-22 at 12 29 17 PM](https://user-images.githubusercontent.com/29099466/164756241-ba0a275e-0380-4666-a373-996f7d4fa44e.png)

**Comment by KateChuen** [comment] 2022-05-03 18:37
Tested on develop branch, using yarn.

- Before the config:
![Screen Shot 2022-05-03 at 2 17 39 PM](https://user-images.githubusercontent.com/45409515/166518144-015b7cb1-4f63-41e8-9ee2-31b96e5032b3.png)


- Setting pagesize = 20
![Screen Shot 2022-05-03 at 2 16 57 PM](https://user-images.githubusercontent.com/45409515/166518179-0b48d44b-a5ce-442c-9e7b-93006d8d7a1a.png)


- Setting pagesize = 10
![Screen Shot 2022-05-03 at 2 16 31 PM](https://user-images.githubusercontent.com/45409515/166518212-10e0c701-5acf-4382-8852-b9836fa443d2.png)


- Setting pagesize = 5
![Screen Shot 2022-05-03 at 2 15 50 PM](https://user-images.githubusercontent.com/45409515/166518261-6b1033ad-f655-4829-97e8-b9ec42136ce3.png)


- Setting pagesize =1
![Screen Shot 2022-05-03 at 2 27 15 PM](https://user-images.githubusercontent.com/45409515/166518672-3f4dde56-b202-435e-bf02-6b043a6755ab.png)


- Setting pagesize = 0, 26 and 50 gives the same result:
![Screen Shot 2022-05-03 at 2 19 30 PM](https://user-images.githubusercontent.com/45409515/166518104-737cebf9-ecc4-4eeb-8988-c55ae76f250b.png)


- Setting page size = 25
![Screen Shot 2022-05-03 at 2 21 31 PM](https://user-images.githubusercontent.com/45409515/166518037-8efd8072-a3bc-4159-9021-3671b660461e.png)
![Screen Shot 2022-05-03 at 2 21 25 PM](https://user-images.githubusercontent.com/45409515/166518046-c3079400-df65-4afe-abe8-fc4b6e01624a.png)

- Setting page size = -25 does not load the components on the page. @bgambocjaviniar can you confirm this is the expected behaviour please?
![Screen Shot 2022-05-03 at 2 22 27 PM](https://user-images.githubusercontent.com/45409515/166518022-699a0d50-ef6b-4f15-809d-86f84d0c48dd.png)

**Comment by KateChuen** [comment] 2022-05-04 19:11
Confirmed with Wei that when it's -ve, then no ids are retrieved, thus nothing is loaded.
