### ISSUE TITLE
B2B Checkout - Console Error Upon Logout

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9173] opened 2020-10-05 10:46 UTC
**Steps to Reproduce:** 
1. Navigate to B2B powertools storefront. 
2. Login and add products to cart. 
3. Checkout. 
4. In order confirmation page, logout. 

**Expected:**
4. No errors in console log. 

**Actual:** 
4. Undefined property error in browser's console. 

Functionality works as expected.
Console error should be removed.

**Comment by giancorderoortiz** [comment] 2020-10-05 10:46
@LTiger14

**Comment by giancorderoortiz** [comment] 2020-10-05 10:49
![Screen Shot 2020-10-05 at 6 43 27 AM](https://user-images.githubusercontent.com/46171897/95070944-e8985f00-06d6-11eb-9c1f-b3fcf3cdf847.png)
![Screen Shot 2020-10-05 at 6 43 44 AM](https://user-images.githubusercontent.com/46171897/95070948-e930f580-06d6-11eb-8fa1-6332c648c5d6.png)

**Comment by bgambocjaviniar** [comment] 2020-10-06 15:37
closing as duplicate of https://github.com/SAP/spartacus/issues/8881

and this was not a b2b checkout bug but a bug that existed pre-b2b checkout merge

**Closed as completed by bgambocjaviniar** 2020-10-06 15:37 UTC
Labels: bug, b2b-checkout
