### ISSUE TITLE
E2E Tests Require Cypress 3.4.1. Version. Guest/Express Checkout Failure

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#5771] opened 2019-12-12 10:58 UTC
Dev has recommended that e2e cypress tests run with version 3.4.1. 
Cookie errors seen in guest checkout and express checkout tests among others. 

![Screen Shot 2019-12-12 at 6 00 44 AM](https://user-images.githubusercontent.com/46171897/70706861-cdbab100-1ca4-11ea-8a91-327b88707837.png)

package.json in projects/storefrontapp-e2e-cypress should have version = 3.4.1. for now until further investigation is done.

**Comment by giancorderoortiz** [comment] 2019-12-12 11:00
See #5737 and #5736

**Comment by Platonn** [comment] 2019-12-12 15:36
Cookies are validated against standard RFC 6265 since cypress PR is merged https://github.com/cypress-io/cypress/pull/5297
Our cookie values contain serialized JSON with quotes, i.e. `{"checkout":{"express":true}}`, which is now forbidden.

See https://stackoverflow.com/questions/1969232/what-are-allowed-characters-in-cookies
> In 6265 the cookie name is still specified as an RFC 2616 token, which means you can pick from the alphanums plus:
> 
> !#$%&'*+-.^_`|~
> In the cookie value it formally bans the (filtered by browsers) control characters and (inconsistently-implemented) non-ASCII characters. It retains cookie_spec's prohibition on space, comma and semicolon, plus for compatibility with any poor idiots who actually implemented the earlier RFCs it also banned backslash and quotes, other than quotes wrapping the whole value (but in that case the quotes are still considered part of the value, not an encoding scheme). So that leaves you with the alphanums plus:
> 
> !#$%&'()*+-./:<=>?@[]^_`{|}~

**Comment by marlass** [comment] 2020-05-08 09:45
Fixed long time ago.

**Comment by Platonn** [comment] 2020-05-08 09:46
Duplicate of https://github.com/SAP/spartacus/issues/5736

**Closed by marlass** 2020-05-08 09:45 UTC
Labels: bug, e2e-tests
