### ISSUE TITLE
[Windows/Firefox] After placing order in guest checkout, can't create account [dupe]

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#10462] opened 2020-12-17 09:58 UTC
**Describe the bug**
After completing the guest checkout process, we are asked to complete the password fields to create an account. Nothing happens after completing this and submitting. 

Note: The email of an existing account was used to complete guest checkout.

**Tell us the version of Spartacus**
- Library version: 3.0.0-rc.4

**To Reproduce**
1. On apparel store, complete guest checkout
2. After placing order and asked "Create an account?", fill the password fields and attempt to submit.

**Expected behavior**
We should have some sort of confirmation of account creation (notification of success and redirection to login page/notification of failure).

**Screenshots**

![image](https://user-images.githubusercontent.com/11735817/102472532-a84e4900-4056-11eb-9dfd-4e6091f61f82.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Comment by Xymmer** [comment] 2020-12-17 13:12
duplicate of #10460, post 3.0

**Closed as completed by Xymmer** 2020-12-17 13:12 UTC
Labels: bug
