### ISSUE TITLE
Tablet view - Add to cart button is being wrapped in wishlist page

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#13161] opened 2021-07-16 15:59 UTC
**Describe the bug**
Using my ipad 12.9', the add to cart text button is being wrapped.
The text is not being wrapped in similar add to cart button instances, such as the product listing page and details page.

**To Reproduce**
1. Go to wish list
2. see the text being wrapped in the button

**Expected behavior**
The text should be in one line like other buttons in Spartacus.

**Additional context**
It occurred using my tablet, but it is reproducible by changing the width of your browser between  (992 and 1012) px
Not related to blue theme

**Screenshots**
![image](https://user-images.githubusercontent.com/29099466/125975640-494c018d-4fd1-4da4-898c-2d5fcba9a849.png)

**Comment by Xymmer** [comment] 2022-03-29 23:41
related or dupe of https://github.com/SAP/spartacus/issues/15327?

**Comment by barteturek** [comment] 2022-04-13 06:34
At the current state of the develop the bug does not longer occur on the wish list. Solution for the problem with misalignment of text in add-to-cart button for other views is proposed here #15327. Task regarding the same problem related to other button groups #15357. The issue can be closed.

**Comment by Xymmer** [comment] 2022-04-13 18:22
closing! thanks

**Closed as completed by Xymmer** 2022-04-13 18:22 UTC
Labels: bug, styling, Minor
