### ISSUE TITLE
[quantity counter issue] Cart with multiple entries with the same product working wrong

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#9134] opened 2020-10-02 07:41 UTC
**Describe the bug**
If there is situation that in cart there are different entries but with the same product. Counter is working wrong, it is getting from first entry product quantity. Once you are inceasing or decreasing product count it is also updating another entry.

**To Reproduce**
(It is not possible to reproduce without Hybris/BE setup)
1. Create promotion that if you add for example 10 the same products to cart you will get 1 exactly the same product as bonus
2. You should see new entry in cart with the same product
3. Item counter will show for both entries value 10
4. If you increase main product quantity by 1 you will see the same quantity value for second entry.

**Expected behavior**
There should be no reference between same products in different entries in cart. If you update quantity for one product it should update only this entry.

**Desktop (please complete the following information):**
OS: Windows 10 Pro
Browser Google Chrome 5.0.4183.121 version
Spartacus Version 2.0.5

**Additional context**
In ``CartItemListComponent`` there is ``createForm`` method with is creating FormControl with key as product code. Which in described scenario above will create multiple FormControl with the same key as productCode. As right now there is no other uniqe parameter for product or for entry. FormControl should be generated with entryNumber as key. THan method ``getControl`` will not broke the cart.

**Comment by Xymmer** [comment] 2020-10-07 13:59
This might be fixed with updates coming soon, we'll retest when that's done and refine this ticket and what to do.

@dydome Can you provide screenshots of what the problem is so we are sure we understand?

**Comment by Platonn** [comment] 2020-10-07 15:00
Perhaps related issue https://github.com/SAP/spartacus/issues/7347 
Currently it's fixed only on the epic branch `epic/product-configuration`. See commit https://github.com/SAP/spartacus/commit/305cce3dc1d3e25321e06ad34145a465ee4a0b1e
The above fix is a breaking change, so if we want it soon, it would be good to fix it in 3.0.
@dydome, if you can't wait for the release of 3.0, you can get inspired by the commit mentioned above and fix it in your customized code.

**Closed as completed** 2020-10-08 15:08 UTC
Labels: bug, breaking-change, cart

**Comment by Platonn** [comment] 2020-10-08 15:45
**QA steps:**
1. go to PDP of `PowerShot A480 (code 1934793)` http://localhost:4200/electronics-spa/en/USD/product/1934793/PowerShot%20A480
2. and add it to cart.
3. close the modal
4. add it to cart again (observe modal again)
5. go to cart page
6. verify you see 2 separate cart entries for the same product (it's OK, becuase this product is configured in backed not to merge entries when adding to cart).
7. Change the quantity of one of the entries to 2 or whatever else different than 1.
8. **Expected:** The quantity for the other entry doesn't change. Only the quantity for the actual modified entity.

Note:
While testing, you may observe another bug in the addded-to-cart modal. It will be addressed in a different ticket https://github.com/SAP/spartacus/issues/9247

**Comment by psmul** [comment] 2020-10-14 08:41
QA done. Works as intended.
