### ISSUE TITLE
Preliminary manual testing of 2.0 May 13-15

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#7614] opened 2020-05-13 14:53 UTC
Based off of #7126

We'll do a preliminary round of manual testing.

Servers:
- Dev3: 2.0 with 1905 (with smartedit)
- Dev8: 2.0 with 2005

Tests:
- [ ] Cancel/Return (GC)
- [x] Smartedit (Wei lead, but get someone else to do it) (Kate)
↪️[Kate]: Against 2005, I get this error. And the page keeps loading in smartedit. Maybe it's because my spartacus is on a different server (frontend dev10, backend dev7)? I'll try (with both frontend and backend) on dev8 once it's setup. I don't want to mess with dev7. 
```
Uncaught Error: https://dev-com-7.accdemo.b2c.ydev.hybris.com:9002 is not allowed to override this storefront.
    at webApplicationInjector.js:9
```
- [x] Qualtrics (Brian) (not needed, e2e tests covering)
- [x] Coupons (Kate) -> Was tested only against 1905
↪️[Kate]: I've never tested coupons on spa before, so not sure how it should work. So I'm following the e2e tests:
There's no "You saved $xx.xx" sentence even though there's the "Applied coupon xxxxx" one.
https://github.com/SAP/spartacus/issues/7649
- [x] Accessibility (checkout with keyboard nav on all 3 browsers) (Bill)
(includes broken tabbing order ticket (related to e2e accessibility? kacper fixing?)
- [x] Checkout as a persistent user (Kate)
- [x] Run e2e against 2005 and add summary of what we need to manually test here (Brian)

**Comment by bgambocjaviniar** [comment] 2020-05-14 20:56
**Run e2e against 2005 and add summary of what we need to manually test here (Brian)**

Using build 20-23 inclusive for better analysis (4 builds) from the job on jenkins `spartacus-regression-test-2005` 
on develop against a 2005 server

two categories: consistent and inconsistent (flaky)

**### [] consistency** 

same test were failing except the one mentioned in inconsistency
this is a good thing as we can have some confidence in our e2e test

- mobile/desktop - asm: failing due to asagent being disabled **(sample data?)**
- mobile/desktop - cart: failing due to test product with stocks when the product should have been out of stock **(sample data)**
- mobile/desktop - consignment-tracking: failing due to non-existent user being used **(sample data - missing consignment e2e test data)**
- mobile/desktop - my-interests: failing due to product that needs to be out of stock has stock **(sample data)**
- mobile/desktop - stock-notification: failing due to product that needs to be out of stock has stock **(sample data)**
- mobile/desktop - save-for-later: either a bug or cypress persistency bug as the save-for-later item from cart did not merge with the new cart. It is most likely cypress. Moreover, it is flaky at times when placing an order due to no waits **(bug / cypress?)**
- desktop - anonymous-consent-config: failing due to consent of terms & condition not transferring (**config issue can't pinpoint what because it doesn't work manually on dev7, but works properly on dev17)**
- desktop - anonymous-consent-flow: same issue as above
- desktop - infinite scroll:  it's broken as in it doesn't scroll. Doesn't scroll because the breadcrumb is still empty **(bug - improvement)**
- desktop - product-details: we don't have apparel enabled **(sample data)**
- desktop -currency-cart-page: $$$ being wrong **(sample data)**
- desktop - store-finder: no idea but it hasn't been working for months on a 2005 server **(backend issue)**
- desktop - apparel-checkout and apparel checkout-guest: we don't have apparel enabled **(sampledata)**


**### [] inconsistency (flaky)**
- only wishlist failed in the last build, which was unusual. Basically, it is flaky.

CONCLUSION
- a lot of sample data issue
- a few bugs
- and a flaky test
- no apparel on dev7

TO TEST: 
- asm
- stock notification
- save-for-later
- consignment-tracking
- storefinder
- cart

**Comment by giancorderoortiz** [comment] 2020-05-21 09:57
Waiting for branch's final changes. 
https://github.com/SAP/spartacus/tree/feature/GH-7375_installation_script
https://github.com/SAP/spartacus/pull/7433

Servers dev-com2,5,8,16 deployed with branch. 
Not operational yet. 
Almost there.

**Closed as completed** 2020-05-22 14:22 UTC
Labels: team/gladiators
