### ISSUE TITLE
[triage needed] Module not found: Error: Can't resolve "site-context-params.service"

### ISSUE THREAD

**Issue by adriankremer** [SAP/spartacus#10706] opened 2021-01-14 14:12 UTC
The documentation says that if one want's to use the StatePersistenceService, one has to use the SiteContextParamsService Injectable to get the current SiteContext.

Importing the SiteContextParamsService results in errors, since it is not exported.

Am I doing something wrong?
(by anthe way thks for spartacus)

**Comment by marlass** [comment] 2021-04-23 11:11
SiteContextParamsService was added to public API in 3.2.0 release, so there shouldn't be problems now with referencing it.

Also duplicate of #10707

**Closed as completed by marlass** 2021-04-23 11:11 UTC
Labels: bug, public-api
