### ISSUE TITLE
Add Schedule Replenishment Documentation

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10092] opened 2020-11-29 17:08 UTC
Create documentation for B2B feature: schedule replenishments

**Comment by bgambocjaviniar** [comment] 2020-11-29 17:57
duplicate of https://github.com/SAP/spartacus/issues/10010

**Comment by bgambocjaviniar** [comment] 2020-12-01 19:50
closing because of the duplicate ^

**Closed as completed by bgambocjaviniar** 2020-12-01 19:50 UTC
Labels: doc, release-activities, b2b-scheduled-replenishment
