### ISSUE TITLE
A11Y. Previous/Next buttons in wrong place

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11242] opened 2021-02-23 19:03 UTC
**Setup**
3.1.0.RC2 Server Links
CCV2 (CX 2011.1):
-- b2c - https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/
-- b2b - https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/

 Linux (CX 2005.6):
-- b2c - http://spartacus-dev2.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/
-- b2b - http://spartacus-dev2.eastus.cloudapp.azure.com:5200/powertools-spa/en/USD/

Comments from @developpeurweb : 
"...not as per mockups, this is crucial because it forces a keyboard user to tab backwards after selecting options to continue with the process. Problem will be bigger for blind users getting to the "Next" button first without realizing all the options under the buttons"

**Comment by Larisa-Staroverova** [comment] 2021-02-24 10:34
Which mockups do you refer? Could you add a screenshot?

**Comment by Larisa-Staroverova** [comment] 2021-02-24 10:56
We got a feedback from @Krzysztof that we should use secondery button for _Previous_ and _Next_ buttons.

**Comment by giancorderoortiz** [comment] 2021-02-24 17:54
@developpeurweb please include mockups in ticket so we can compare with implementation

**Comment by developpeurweb** [comment] 2021-02-24 20:20
Found this mockup below in Zeplin, which as is, would be a logical sequence keyboard pattern, pls @Manurod2018 @vekterdude can you confirm I have the right one.

The issue is regarding the position of the buttons being currently (in the video) at the top instead of at the bottom. As shown in the video this forces the user to tab backwards in order to go forward in the process. This is currently just a bad non-sequential keyboard pattern, but it will be a hard-bug once we upgrade to screen reader's support.

To reproduce see video: https://video.sap.com/media/t/1_ghzw77ig 
It's basically all over the video, but indeed gets worst when having a long list of options, like at minute `16:33`

![Screen Shot 2021-02-22 at 2 21 43 PM](https://user-images.githubusercontent.com/15113219/109057453-bdc39d00-76af-11eb-8a72-39910ce36522.png)

**Comment by Manurod2018** [comment] 2021-02-24 21:01
@developpeurweb, yes it looks like you have the right screens, they are all in Zeplin: Zeplin: https://zpl.io/bzj5qyA

**Comment by Larisa-Staroverova** [comment] 2021-02-25 11:32
@giancorderoortiz, could you trigger the new deployment, the fix is merged into **spartacussampledata** **release/2005/next**.
Please, retest as soon as **#11266** is closed and **spartacussampledata** is newly deployed to the environment.

**Comment by Larisa-Staroverova** [comment] 2021-03-24 06:53
Verified after fix, the previous and next buttons are placed as expected:
![image](https://user-images.githubusercontent.com/61147963/112267616-09994000-8c76-11eb-9ae3-0fb7ed1c8089.png)

**Closed as completed** 2021-03-24 06:53 UTC
Labels: bug, a11y, product-configurator
