### ISSUE TITLE
SSR breaks on v4.0.1 with a custom i18n backend config

### ISSUE THREAD

**Issue by rpisarew** [SAP/spartacus#13643] opened 2021-09-08 10:47 UTC
**Describe the bug**

After a update to v4.0.1 the SSR rendering timeouts for every request as long I have a custom backend config for the i18n translations like this:

```typescript
    provideConfig({
      i18n: {
        backend: {
          loadPath: 'assets/translations/{{lng}}/{{ns}}.json',
        },
        ...
      },
    })
```

I have no errors for missing translations or chunks, I just get the message that the SSR fallbacks to CSR. If I comment out the backend configuration, I get errors for missing translations as expected, but the SSR works. Any idea how I can debug this?

**Tell us the version of Spartacus**

v4.0.1

**Steps to reproduce the behavior:**

1. create a new app with SSR
2. add a custom backend configuration for i18n
3. do a request e.g. with curl

**Expected behavior**

The site should render with SSR.

**Workaround**

When I embed the translations in the configuration like that, it works:
```typescript
    provideConfig({
      i18n: {
        resources: {
          de: { ... },
          en: { ... },
        },
        ...
      },
    })
```

**Comment by Xymmer** [comment] 2021-10-27 19:30
probably a duplicate of #12293, check to be sure, we'll close the other one

**Comment by rpisarew** [comment] 2021-10-27 19:41
I thought the same, but unfortunately I have no missing chunks. I get no errors or any messages in the console. The same translations concatinated in one file (exported as one big json) and embedded in the code as described above, just works.

I tried it even with an clean project and I had the same behaviour.

**Comment by peebeebee** [comment] 2021-12-23 08:33
Also see this: https://github.com/SAP/spartacus/issues/14372

**Comment by Platonn** [comment] 2022-07-05 11:39
Duplicate of #14372

**Closed as completed by Platonn** 2022-07-05 11:39 UTC
Labels: bug, SSR, Major
