### ISSUE TITLE
Not existing order number id - an empty order history details page visible

### ISSUE THREAD

**Issue by zuzanna-bialecka** [SAP/spartacus#15809] opened 2022-06-02 09:24 UTC
**DESCRIPTION**
Upon entering the order details page for non existing order number instead of a 404 an empty page with partially filled in values is visbile

**VERSION**
- Library version: 4.3.4

**STEPS TO REPRODUCE**
1. Go to my account / order history
2. Enter the order details page for existing order
3. Enter the order details page for NON existing order (url containing invalid order number)
4. The order details page is visible with pre-filled values

**Expected behavior**
Upon entering the order details page for non existing order number a 404 page not found should be visible 

**Screenshots**

![ORDER DETAILS](https://user-images.githubusercontent.com/106664100/171599472-0b010309-fa35-41d1-b0b1-77ff80af3299.jpg)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: chrome, safari, firefox

**Comment by Xymmer** [comment] 2022-07-13 17:50
duplicate of #11433, closing

**Closed as completed by Xymmer** 2022-07-13 17:50 UTC
