### ISSUE TITLE
My coupons e2e test failing

### ISSUE THREAD

**Issue by qjimmy** [SAP/spartacus#6465] opened 2020-02-10 18:33 UTC
Duplicate e2e test? There is the file **cypress/integration/mobile/my-coupons/my-coupons-mobile.e2e-spec.ts** and **cypress/integration/mobile/my-account/my-coupons-mobile.e2e-spec.ts** (basically same file but one under folder my-account and the other under the folder my-coupons) is this intentional or a mistake? Investigation needed.

Regression version: **cypress/integration/regression/my-coupons/my-coupons.e2e-spec.ts**

Invalid credentials error when logging in?

<img width="1078" alt="Screen Shot 2020-02-10 at 1 24 06 PM" src="https://user-images.githubusercontent.com/30666844/74177864-8f8c3000-4c08-11ea-9f0e-5c8edae4b60e.png">

Backend: **Dev12**

**Comment by hackergil** [comment] 2020-02-11 20:04
I fixed a couple of assertions, but still a couple of tests are failing. Can someone from the KungFu team have a look and let me know if the test is wrong or something with the coupon is wrong?

**Comment by hackergil** [comment] 2020-02-19 19:12
Kung Fu team fixed these. Here's what happened:

The test data for coupon include some promotions which should be published, then the functions can work well.

- If the test data is imported when installing sampledata addon, then the promotions will be published automatically.
- If you import the test data manually, promotions are unpublished, you should publish them manually.

Promotions need to be re-enabled manually and a reindex of electronics is also required.

**Comment by plabadie** [comment] 2020-02-20 15:33
Still fails 1.5.x

https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-maintenance/22/consoleText

**Comment by reyhanehsalkhi** [comment] 2020-02-21 18:20
In the last run of the job, the test has passed, also its passing on local run of test.
Closing it for now.

**Comment by reyhanehsalkhi** [comment] 2020-02-21 20:42
I ran the test 40 times and all passed on local against dev 12. Also the test has passed in the last run of the job. 

closing the issue for now.

**Comment by reyhanehsalkhi** [comment] 2020-02-21 21:05
After multiple runs of the test was able to reproduce locally. 
The error is 
"Unable to find an element with the text: Set as default. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible."

We need to use a more specific matcher. 

`cy.getByText('Add New Payment').click({ force: true });
`
it should be 

```
cy.get('.cx-checkout-btns')
    .getByText('Add New Payment')
    .click({ force: true });
```

same if true about the delete button.

**Comment by plabadie** [comment] 2020-02-24 22:05
Tests fail on 1.5.x branch
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-maintenance/31/consoleText

**Comment by qjimmy** [comment] 2020-03-04 18:54
Failing on maintenance branch again because server is very slow to serve responses

**Comment by bgambocjaviniar** [comment] 2020-03-25 06:38
PR: GH-7060

**Closed** 2020-03-27 07:29 UTC
Labels: 1.5-e2e, MUST, e2e-develop-branch, e2e-maintenance-branch, e2e-tests
