### ISSUE TITLE
Double routing navigation to the 'payment details' checkout step

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#8258] opened 2020-07-17 16:05 UTC
**Describe the bug**
When going from Delivery Mode to Payment Details checkout step, there is a redundant navigation in backgound, which is not optimal.

**To Reproduce**
1. Log any `NavigationStart` router event to the console, by adding temporarily a `constructor` to your app.module:
    ```typescript
    export class AppModule {
      constructor(router: Router) {
        router.events
          .pipe(filter((event) => event instanceof NavigationStart))
          .subscribe(console.log);
      }
    }
    ```
2. Open storefront and console in chrome dev tools
3. Add product to cart
4. Go to cart page
5. Proceed through checkout steps:
  a) shipping addres... and click [Continue] button
  b) delivery mode... and click [Continue] button
  c) you are on the payment details step
6. Observe in the console double navigation entry to `/checkout/payment-details`
  

**Expected behavior**
Ony one navigation entry to `/checkout/payment-details`

**Screenshots**
![image](https://user-images.githubusercontent.com/4001059/87806893-d9341300-c857-11ea-8028-a95d34b426c6.png)

**Additional context**
The checkout steps are orchestrated by the guards assigned in `cmsComponents` and checkout config https://sap.github.io/spartacus-docs/extending-checkout/

**Comment by Xymmer** [comment] 2020-11-24 14:56
retest if this is still happening
proooobably not happening anymore due to change by Marcin

**Comment by giancorderoortiz** [comment] 2020-11-25 14:19
Please add app.module.ts file with modifications mentioned in description. 
Getting compilation errors. Perhaps missing an import.

**Comment by giancorderoortiz** [comment] 2020-12-03 16:54
I still see issue. Develop branch. Dec 2nd. 
![Screen Shot 2020-12-03 at 11 52 09 AM](https://user-images.githubusercontent.com/46171897/101061234-42de6080-355e-11eb-8c17-aa1d1ca637aa.png)

**Comment by wangzixi-diablo** [comment] 2021-02-02 07:54
Hello @Platonn 

I have pulled latest code from develop branch and have a retest, and I could NOT reproduce this issue from my side: only one routing navigation entry for payment details checkout step observed in Chrome console.

Kindly see screenshot below:

![image](https://user-images.githubusercontent.com/58975336/106568894-dd631c00-656e-11eb-9a3c-362a9fa7da6b.png)


Best Regards,
Jerry

**Comment by giancorderoortiz** [comment] 2021-06-06 14:44
Closing per @wangzixi-diablo 's comments.

**Closed as completed by giancorderoortiz** 2021-06-06 14:44 UTC
Labels: bug, checkout, routing, performance, Minor
