### ISSUE TITLE
Missing i18n translation chunk breaks SSR rendering

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#12293] opened 2021-05-05 08:17 UTC
For applications configured with lazy loaded translations (static json assets files) the client side application works OK (missing json assets is reported in the console) but SSR rendering breaks (plenty of unrelated http requests fails and render is not finished).

**Comment by giancorderoortiz** [comment] 2021-06-06 23:12
@Xymmer severity of this issue should be changed.

**Comment by jamesgarzon** [comment] 2021-09-04 00:01
I have the same issue, these are the logs we could extract that may help you 

[logs.txt](https://github.com/SAP/spartacus/files/7108926/scratch_230.txt)

Do you know a workaround while you fix this?

**Comment by Xymmer** [comment] 2021-10-26 15:38
this was set to minor, but can't remember the reason for that... let's discuss in triage

**Comment by Xymmer** [comment] 2021-10-27 19:31
very likely duplicate of #13643, closing this one, we'll fix in other ticket

**Closed as completed by Xymmer** 2021-10-27 19:31 UTC
Labels: bug, i18n
