### ISSUE TITLE
Remove cart item does not work if cart has more than one item

### ISSUE THREAD

**Issue by AlexanderKuschner** [SAP/spartacus#11425] opened 2021-03-09 09:00 UTC
Add more than one item to the cart.
Press remove link for the first one -> quantity is set to '0', but the item is not removed. Only after refresh the item disappears.

Can be seen in develop in b2b and b2c, and also happens if the product configurator feature is not active at all.

**Comment by Zeyber** [comment] 2021-04-16 10:47
Closing as I can't replicate this issue.

**Closed as completed by Zeyber** 2021-04-16 10:47 UTC
Labels: bug, esc, esc-for-3.4

**Comment by giancorderoortiz** [comment] 2021-05-18 12:01
Unable to reproduce. I see this issue as working. 
Tried with a cart that has 100+ SKUs. 

Initial condition here: 
![cart_init](https://user-images.githubusercontent.com/46171897/118647263-256d1e00-b7af-11eb-8f93-46e73ad0251e.png)


Then changed qty of NV10 camera to 0 and pressed enter. 
Item was removed: 

![cart_after_qty_zero_first_sku](https://user-images.githubusercontent.com/46171897/118647330-39188480-b7af-11eb-9d23-fd70e6a13e3f.png)


Then clicked on remove on yellow camera. Item removed as well. 
![cart_after_remove_yellow_camera](https://user-images.githubusercontent.com/46171897/118647390-49c8fa80-b7af-11eb-8d77-c40bf62f2e84.png)

**Comment by giancorderoortiz** [comment] 2021-05-18 12:02
@Larisa-Staroverova @ChristophHi  see comments from ticket author regarding seeing this issue in product configurator as well. I don't see it in develop branch (May 17th, 2021).
