### ISSUE TITLE
Wrong parameter in components request on product not found page

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#9133] opened 2020-10-02 07:26 UTC
**Describe the bug**
Error page template is not rendering once you are trying to enter product page with wrong productCode. Looks like page context is not updating.

**To Reproduce**
1. Go to product page.
2. Replace productCode in url with random characters.
3. Go to that page.
4. See blank page, with error on pages request.

**Expected behavior**
It should navigate to ErrorPageTemplate.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Google Chrome 5.0.4183.121 version
 - Spartacus Version 2.0.5

**Additional context**
IT looks like in ''OccCmsComponentAdapter'' method ''getContextParams'' is trying to get product ID as this is product page, but because of that error page cannot load properly.

**Comment by Xymmer** [comment] 2020-10-07 13:50
We need to update how this works so that we show "not found" under the (incorrect) url. We'd also want to allow customers to take control of this response to display for e.g. "customers also viewed" or "products similar to the one you were looking for". We get bad request from occ so we'd have to do something special to capture that it's a product page being requested... needs refinement. Setting to feature improvement.

When someone takes this ticket, maybe talk to Stan and Kris and Bill.

**Comment by dydome** [comment] 2020-10-16 11:42
@Xymmer it looks like this is a bigger issue than we thought. Our client discovered another case where this problem persists. Imagine than one product which exist before, now is not available in Hybris any more, but somebody enters directly url with the product code. Then again, he should be navigate to 404 page, but he isn't. Spartacus is crashing.

You can try to do it on your official demo instance, go to:
https://spartacus-training.eastus.cloudapp.azure.com/electronics-spa/en/USD/product/300938/Photosmart%20E317%20Digital%20Camera

Than change url to (**_change product code_**):
https://spartacus-training.eastus.cloudapp.azure.com/electronics-spa/en/USD/product/test/Photosmart%20E317%20Digital%20Camera

What happened:
1) There is a call to pages with 400 errors
2) Than there is a new call for pages with _**not-found**_ pageLabelOrId field
3) Than as always, component call is comming, but it has old product page context with **_productCode: test_**

What should have happend:
After a call to pages for 404 pages, page context should be cleaned. So probably that action should happen in **_CmsPageGuard_** or **_CmsPageGuardService_**

![image](https://user-images.githubusercontent.com/18736434/96254325-6735ac00-0fb5-11eb-8279-824f8e2df080.png)

**Comment by dunqan** [comment] 2020-11-18 10:05
Duplicate of #9617

**Comment by dunqan** [comment] 2020-12-04 07:46
Fixed in 3.0 by #10178.

**Closed as completed by dunqan** 2020-12-04 07:46 UTC
Labels: bug
