### ISSUE TITLE
[repro] Site freezes when logging out of ASM

### ISSUE THREAD

**Issue by csqbk** [SAP/spartacus#14914] opened 2022-01-31 13:26 UTC
**Describe the bug**
At the moment of logging in as asm with any account and later, closing said session, if we try a search in the searchbox or go to another page we will see that we will not be able to do it.
If we look at the 'Network' tab of the DevTools we will see that no requests are executed, and it seems that in Redux, the navigations are canceled and the "Load Page Data" action never fails or completes successfully.

**Version of Spartacus**
- Library version: 3.4 but I was also able to reproduce the bug in the [Spartacus Demo](https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/)

**To Reproduce**
1. Login in ASM mode
2. Log out of ASM
3. Try performing a search in the searchbox or go to another page (e.g, the PDP of a product)

**Expected behavior**
That when you log out of ASM you can navigate correctly through the site

**Desktop:**
 - OS: Linux Ubuntu 20.04 LTS and Windows 10
 - Browser: Chrome, Firefox and Edge

**Comment by Xymmer** [comment] 2022-02-07 18:56
thanks @csqbk... any chance you can record network activity and send us .har file?

**Comment by Xymmer** [comment] 2022-02-07 18:56
gc thinks cors issue.... retest so we can get more logs/info.

**Comment by csqbk** [comment] 2022-02-10 21:00
Hi @Xymmer , thanks for replying.
I don't recall seeing CORS errors in network activity.

I was able to find a solution that works for now, but I'm not sure if there are any side effects.

Apparently, in the logout flow like ASM, the **revokeAndLogout** method fires 2 times.
The first time occurs inside the **CsAgentAuthService**, in the **logoutCustomerSupportAgent** method. The second time happens inside the **AuthService** in the **coreLogout** method.

The problem is that when we start a second **revokeAndLogout** process, we are trying to delete a token that we already deleted in the first call, this causes that inside the **AuthHttpHeaderService**, in the stopProgress$ observable we never close the logout process.
This causes that within the **AuthInterceptor**, when trying to obtain the token through the **getStableToken** method, we never get it.

The solution I came up with was that the first call of the **revokeAndLogout** method is only done when emulating a user.

 ```
async logoutCustomerSupportAgent(): Promise<void> {
    const emulatedToken = this.authStorageService.getEmulatedUserToken();

    let isCustomerEmulated: boolean;
    this.userIdService
      .isEmulated()
      .subscribe((emulated) => (isCustomerEmulated = emulated))
      .unsubscribe();

    if (isCustomerEmulated && emulatedToken) {
      await this.oAuthLibWrapperService.revokeAndLogout();
    }

    this.store.dispatch({ type: '[Auth] Logout Customer Support Agent' });
    this.authStorageService.setTokenTarget(TokenTarget.User);

    if (isCustomerEmulated && emulatedToken) {
      this.store.dispatch(new AuthActions.Logout());
      this.authStorageService.setToken(emulatedToken);
      this.userIdService.setUserId(OCC_USER_ID_CURRENT);
      this.authStorageService.clearEmulatedUserToken();
      this.store.dispatch(new AuthActions.Login());
    } else {
      this.authService.logout();
    }
  }
```

**Comment by plabadie** [comment] 2022-03-31 23:08
The PR provided makes the issue go away.  That works well.

My concern is that by fixing the logout guard, we do fix the ASM logout issue, but we don't fix the bug itself, which seem to be that when we call logout twice (or when we call logout for an anonymous user), the Spartacus app freezes.  Could we investigate some alternative solution for the bug that would tackle, if possible, the root cause?  I think it's worth a shot.  

I don't know the exact and single best solution, but here are some pointers/suggestions:

a) Could we evaluate making spartacus resilient to calling the logout function when no user is signed in. We could investigate fixing the mechanism that freezes, apparently an http interceptor.  Otherwise, the solution for that might be suggestion b) below.

b) If we can't fix the logic that freezes, could we evaluate making the fix in the service where the logout function would check if a user is logged-in before performing a logout.  This way at least all the callers, like the logout guard would benefit from the fix.

c) Regardless of the above, we might also want to investigate why ASM calls logout twice when it should be once and fix that.

If an alternative solution is found, let's revert the previous PR if it becomes redundant.

**Comment by Xymmer** [comment] 2022-04-22 20:14
Closing this one as i created https://jira.tools.sap/browse/CXSPA-301 and put it in Iceman backlog

**Closed as completed by Xymmer** 2022-04-22 20:14 UTC
Labels: bug, Major
