### ISSUE TITLE
i18n translations cannot be loaded from a dynamic url anymore

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#17124] opened 2023-03-24 11:00 UTC
**Describe the bug**
With Spartacus Version 4.3.7 (and lower versions), it was possible to load the i18n translations by using a dynamic url as endpoint. This was done by using a custom config initializer, where a logic could be defined to use a dynamic url from the occ endpoint config or based on the active base site. 

This case and the formerly working solution for it is described in this [stackoverflow](https://stackoverflow.com/a/67588414/2477219) answer by @Platonn:

```
export class Custom18nConfigInitializer extends I18nConfigInitializer {
  readonly scopes = ['i18n.backend.loadPath']; // declare config key that you will resolve
  readonly configFactory = () => this.resolveConfig().toPromise();

  constructor(
    protected configInit: ConfigInitializerService,
    private occEndpoints: OccEndpointsService,
    private baseSiteService: BaseSiteService
  ) {
    super(configInit);
  }

  protected resolveConfig(): Observable<I18nConfig> {
    return this.baseSiteService.getActive().pipe(
      take(1),
      map(() => {
        return {
          i18n: {
            backend: {
              loadPath: this.occEndpoints.buildUrl('i18n'),
            },
          },
        } as Config;
      })
    );
  }
}
```

```
// i18n config
export function i18nConfigFactory(): I18nConfig {
  return {
    i18n: {
      backend: {
        // placeholder value 'dynamic' get's replaced in the OttosI18nConfigInitializer with the proper OCC url since we need tha base site id in the url
        loadPath: 'dynamic',
      },
      chunks: {
        ...translationChunksConfig,
        cart: [...cartBaseTranslationChunksConfig.cart],
        checkout: [...checkoutTranslationChunksConfig.checkout, 'checkoutGuest', 'checkoutShipping'],
        order: [...orderTranslationChunksConfig.order],
        storeFinder: [...storeFinderTranslationChunksConfig.storeFinder],
        userAccount: [...userAccountTranslationChunksConfig.userAccount],
        userProfile: [...userProfileTranslationChunksConfig.userProfile],
      },
      fallbackLang: 'de',
    },
  };
}
```

```
// app.module.ts
providers: [
    {
      provide: CONFIG_INITIALIZER,
      useExisting: CustomI18nConfigInitializer,
      multi: true,
    },
  ],
```

This requirement is needed, when having different translations per Environment or different translations per Site in a Multi Site / Multi Country Setup.

Since Spartacus 5.0, this approach does not work anymore. When now trying to use a custom config initializer, it seems, that the translation calls are being made, BEFORE the custom config initializer kicks in. The logic in the custom config initializer still works, but it seems to run too late, after the translation calls have already been made. Therefore the translation calls use the backend `loadPath` defined in the static i18n config and not the dynamic one coming from the custom config initializer.

The issue might have something to do with the bigger change done in the area of i18n on Ticket https://github.com/SAP/spartacus/issues/11675.

**Tell us the version of Spartacus**
- Library version: 5.2.0

**To Reproduce**
1. Create a new Spartacus Project
2. Add a custom Config Initializer as defined above
3. Add an i18n config with the `loadPath` option to enable the`i18n` lazy loading (the value for `loadPath` can be something random, as it should be overridden by the custom config initializer)
4. Start your Spartacus locally 
5. Notice that all translation calls are being made to the url defined in the `i18n` config property `loadPath` and not the one coming from the custom config initializer

**Expected behavior**
There is an option to use a dynamic url to load the translations from.

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser: all
 - Version: all

**Additional context**
There is an open [SAP Launchpad Issue](https://launchpad.support.sap.com/#incident/pointer/002075129500002379952023) about the problem, since it blocks us from merging the update branch and also from going live.

**Comment by janwidmer** [comment] 2023-03-24 14:51
It seems that it was working correctly in version 5.0.0.

Test Repositories:
https://github.com/janwidmer/spartacus-i18n-5.0.0
https://github.com/janwidmer/spartacus-i18n-5.2.0 (Bug is fixed by workaround, see [comment](https://github.com/SAP/spartacus/issues/17124#issuecomment-1483046020) below, to see the problem again, remove the provider `I18nextInitializer` in `app.module.ts`

Instructions to test:

1. clone the repo
2. run npm i
3. Notice that with the 5.2.0 Repo, the translation call is done to http://localhost:4200/static/i18n/path/to/i18n-assets (wrong static path as defined in static config
4. Notice that with the 5.0.0 Repo, the translation call is done to https://spartacus-demo.eastus.cloudapp.azure.com:8443/occ/v2/electronics-spa/i18n (correct occ endpoint as defined in custom config initializer, obviously the demo backed does not have the endpoint, but it proofs the point)

**Comment by Platonn** [comment] 2023-03-24 15:27
Hi @janwidmer. Thank you for reporting the issue with details!
By any chance, did you try to debug the the root cause why a custom config initializer is working anymore as expected since 5.2?

**Comment by janwidmer** [comment] 2023-03-24 16:01
Hey @Platonn,

The config initializer is still working, but it get's run AFTER the translation calls are made to the wrong url. It therefore is a timing issue.

I have compared the changes in spartacus core from 5.0 to 5.1 now. I have found out, that in the old version of the code (file `i18next-init.ts` which was replaced in ticket [11675](https://github.com/SAP/spartacus/issues/11675)), the init method was waiting for `configInit.getStable('i18n')`.

In the new code (file `i18next-initializer.ts`) the `initialize` method does not wait for the config to be stable anymore. Therefore the `i18n-next` get's initialized too early and the i18n calls are made before the custom config initialiser runs.

I have added a custom version of the `I18nextInitializer` in my test project https://github.com/janwidmer/spartacus-i18n-5.2.0 locally (not comitted yet) and this seems to fix it:

```
/**
 * Custom init function for the I18nextInitializer to be able to wait for the i18n config to be stable before initializing i18next.
 *
 * This is needed to make custom our custom config initializer work since otherwise the translations calls would be mabe before
 * our custom url is set in the custom config initializer.
 */
@Injectable({ providedIn: 'root' })
export class CustomI18nextInitializer extends I18nextInitializer {
  override initialize(): Promise<any> {
    const configInitializerService = AppInjector.get(ConfigInitializerService);

    return configInitializerService
      .getStable('i18n')
      .toPromise()
      .then(() => {
        const i18nextConfig = this.getI18nextConfig();
        return this.i18next.init(i18nextConfig, () => {
          // Don't use i18next's 'resources' config key for adding static translations,
          // because it will disable loading chunks from backend. We add resources here, in the init's callback.
          this.addTranslationResources();
          this.synchronizeLanguage();
        });
      });
  }
}
```

Little Side note: The Injection Token `I18NEXT_INSTANCE` does not seem to be exported from Spartacus core, therefore I cannot extend the constructor of `I18nextInitializer` to be able to inject the `ConfigInitializerService`, that's the reason why I am using a global `AppInjector` defined in my `app.module.ts`. 

It would be great if this bug could be fixed and backported to Version 5.2.0. 

Thanks for your help.

**Comment by Platonn** [comment] 2023-03-27 08:34
@janwidmer Thank you for your investigation! Also thank you for providing the **workaround** which can by possibly helpful for other community members.

I can't promise in which version it will be fixed or whether the fix will be backported to 5.2 (or only to 6.x). But I'll make sure to prioritize fixing it. 

Many thanks again for your contribution!

**Comment by janwidmer** [comment] 2023-03-27 08:41
@Platonn thanks for your support. Your input, that it was working in version 5.0 pointed me into the direction where to search :).

Thanks also for priorizing the issue. It would be great if also the injection token `I18NEXT_INSTANCE` would be correctly exported, so I could remove the hacky workaround with the global AppInjector.. ;-)

Best Regards
Jan

**Closed as completed** 2023-03-28 10:40 UTC

**Comment by Platonn** [comment] 2023-03-28 16:04
Hi @janwidmer 
Thanks for suggestion to export `I18NEXT_INSTANCE`. It should be a natural consequence of making the initialization of `i18next` more extendable.

I've merged PR with the export now https://github.com/SAP/spartacus/pull/17142

**Comment by janwidmer** [comment] 2023-03-28 18:17
Hey @Platonn, 

Perfect, thanks for the fast reaction and the support.
