### ISSUE TITLE
Automate tsconfig's paths generation

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#10288] opened 2020-12-09 08:24 UTC
To ease the simultaneous development of our libraries (including debugging) we map imports from libraries to the source code or prod build artifacts which results in complex path mappings in the global project's tsconfig and in the app shell's tsconfig files.  Those entries are a pain to manage manually, we want to automate it for known libraries and their entry points.

**Comment by marlass** [comment] 2020-12-14 11:35
Duplicate of #10355

**Closed as completed by marlass** 2020-12-14 11:35 UTC
Labels: features-libs
