### ISSUE TITLE
[still an issue?] Checkout: Delivery mode checkout step keeps loading

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#8012] opened 2020-06-19 18:14 UTC
We also see this in B2C 2.0

**Environment Details**
Spartacus: epic/b2bcheckout
Browser: Chrome
Device: mac
Happens on: http://dev-com-3.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Should not have any address saved in address book.
- Add item to cart.
- Proceed to checkout
- On step 2, where we choose the delivery mode, it keeps spinning. 

**Actual Result**
Should load the available shipping methods. 

<img width="740" alt="Screen Shot 2020-06-19 at 2 08 13 PM" src="https://user-images.githubusercontent.com/45409515/85167506-ebaa3500-b236-11ea-82e8-f2430d9c61e6.png">
<img width="671" alt="Screen Shot 2020-06-19 at 2 08 36 PM" src="https://user-images.githubusercontent.com/45409515/85167507-ec42cb80-b236-11ea-8742-58b7551068b2.png">

**Comment by giancorderoortiz** [comment] 2020-07-01 12:03
This also happens on develop branch. 
It's a highly intermittent issue. 
Most likely to reproduce if starting from a brand new user. 
Causes some e2e tests that do checkout to fail.

**Comment by giancorderoortiz** [comment] 2020-08-03 21:39
The source of this problem is in the backend. 
See  https://cxjira.sap.com/browse/CMSX-10148 which I had logged a while back. 
An alternative method to force reload (upon failure) of this page must be found.

**Comment by Xymmer** [comment] 2020-08-14 17:13
we concluded it might not be the backend
we can repro under specific circumstances
we can't see this issue in develop
trying to figure out how it was fixed, if it's really fixed

**Comment by Zeyber** [comment] 2020-08-24 11:52
Found the main cause of this is when 400 errors are returned by the backend. Most 400 errors are handled by the front end except for `GET` `deliverymodes?` which causes the app to get stuck on the delivery modes page.

Error is extremely rare but can be replicated if you run `checkout-as-persistent-user` e2e test multiple times (can even take up to 50 times) until you see a 400 error returned from `GET deliverymodes` (not to be mistaken with `GET deliverymode` without 's' which does not stall the app).

![image](https://user-images.githubusercontent.com/11735817/91042607-4f275900-e612-11ea-9c67-ea56c384830e.png)


QA:
- Rerun `checkout-as-persistent-user` e2e test until 400 error is returned by `GET deliverymodes`. Verify the test does not stop working here.

Note: There is another issue that can fail the test that looks like this 
![image](https://user-images.githubusercontent.com/11735817/91042386-efc94900-e611-11ea-9c81-c950fa7b0ed7.png)
It is another issue to be solved in #6696.

**Comment by bgambocjaviniar** [comment] 2020-09-18 21:31
Re-opening ticket as we were able to see the infinite loading spinner even on develop.

Wasn't able to reproduce or know how to reproduce it. There are no errors in the network tab, or any infinite calls as actions in store and network tab. 

Was told to ping Caine with the link to the snippet video we have because it's not upload-able here.

**Comment by Xymmer** [comment] 2020-10-27 16:45
haven't seen this lately, closing

**Closed as completed by Xymmer** 2020-10-27 16:45 UTC
Labels: bug, checkout, delivery-mode, Important/VeryHigh
