### ISSUE TITLE
[Blocked by 5562] SSR in spartacus installation not working from schematics

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#5370] opened 2019-11-12 16:24 UTC
Our spartacus installation script is not installing spartacus with SSR correctly
* The manual steps are outdated
* The schematics fail with the following:

> Installing packages...
            ✅️ Added '@angular/platform-server' into dependencies
            ✅️ Added '@nguniversal/express-engine' into dependencies
            ✅️ Added 'ts-loader' into devDependencies
            ✅️ Added 'webpack-cli' into devDependencies
Cannot read property 'kind' of undefined

I believe this is also a problem with the schematics overall installing the latest beta in a shell app in SSR mode

**Comment by psmul** [comment] 2019-11-13 14:08
Could not reproduce the problem. Tried both ways: building locally schematics lib and using our @spartacus/schematics approach. Can you provide more details? Environment, script used, params or branch?
@hackergil

**Comment by hackergil** [comment] 2019-11-13 16:11
Did you try with a brand new shell app?

**Comment by psmul** [comment] 2019-11-22 12:04
https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/issues/413

**Comment by hackergil** [comment] 2019-11-25 17:12
@psmul Sorry, I didn't get what the fix for this ticket was. Can you clarify?

**Comment by psmul** [comment] 2019-11-25 18:07
@hackergil Mostly just adjusting documentation. Maybe I was too hurry with closing it with mistakenly thinking it's working as I wasn't able to reproduce a problem.

**Comment by psmul** [comment] 2019-11-27 13:09
After some investigation, we've find out that the problem is in angular-cli version. 
For this repo:
https://github.tools.sap/cx-commerce/spartacus-installation
And file: `spartacus.sh`
Please update Angular-CLI version from '~8.0.0' to '~8.2.0'. After that, it all should work fine. Tested locally with different angular-cli versions higher than 8.0.0.

**Comment by hackergil** [comment] 2019-11-28 12:59
After following the above, the script is now failing on the PWA step, as described in #5562. We depend on these changes to fix this.

**Comment by plabadie** [comment] 2021-01-18 22:10
Closing, can't repro. Moreover, the script was updated a lot since 2019 and is not known to fail recently.

**Closed by plabadie** 2021-01-18 22:10 UTC
Labels: bug, ssr, team/blamed
