### ISSUE TITLE
UX for Cart Validation at Checkout (S)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9271] opened 2020-10-09 01:31 UTC
If there are issues with the cart at start of checkout, let's inform the user and be as helpful as possible.
For example, if a product is out of stock, move it to save for later.
https://cxwiki.sap.com/display/spar/Feature%3A+Cart+Validation+at+Checkout

**Comment by jeannewalters** [comment] 2020-10-12 20:16
@Xymmer Assigned to you until the feature specs are ready.

**Comment by Xymmer** [comment] 2020-10-21 14:22
ready

**Comment by medzneel** [comment] 2020-11-30 17:31
UX Spec due - 12/04/2020

**Comment by vekterdude** [comment] 2020-11-30 19:43
Hi Medha,
There are a few events that block the cart that I can think of and may or may not be relevant to your story.

The Configurations Add-On CPS
If a configurable product has an error, or a conflict the product may not be checked out and will block the checkout of the other cart products until all issues are resolved. They are adding bundles to their feature add on so soon it will include a bundled product within the configuration that is out of stock as well! This team may be responsible for their own error messaging that overwrites the cart code when the add-on is installed. Not sure.

A missing bundle item:
Soon we will add bundles to the core product as well. The products will be rolled up under a main product, but we need to investigate what happens if any bundle item selected by the user is no longer in stock. It probably is treated much the same way as any individual product being out of stock but if it is a mandatory product then the bundle is incomplete without it and the checkout is once again blocked.

Regular out of stock items like single sku items.
This is the most common / normal use case.

Items that appear as part of a grid order "rollup" and are entered into the cart as a grouping. In an early phase we may just add them all as individual products, but we should plan for when they are grouped.

Items coming from the wish list.
It would be nice if we could leave wish list items in the wish list and not add them to the cart if we know they are out of stock, but I don't think we do the validation for stock until they are re-added to the cart. Might be nice that if we did that calculation and if the item is not in stock that it never makes it to the cart and the notification states the reason why.

There are also the out of stock at a store (BOPIS) vs. out of stock for delivery to think about. Not sure if they get different treatment, but be aware of the issue. If the item is to be picked up in store it doesn't matter that it is in stock online, only if it is in stock at the store where it is to be picked up. There is a confirmation email before the customer can pass by the store to get the goods. At that moment the goods are confirmed in stock, but that is after checkout.

Other things that may be "associated with each other" come from verticals - like warranties and service agreements and subscriptions. What happens to the base product if the subscription service is no longer offered, or the associated warrantee etc... This may be the responsibility of the team making the specific add-on. But be aware that this will be future requirement for a verticals team.

Hope this helps. Any questions just call!
Cheers,
Anthony

**Comment by Manurod2018** [comment] 2021-01-21 19:44
Visuals are on Zeplin: https://zpl.io/2ENnmAY
Please select the tag  "#9271" which is the ticket number of that feature to see all related screens. 

Currently, we have one set of notification banners for global alerts related to the entire page. They are usually used for system notifications or other information related to the entire page.
Those can either be dismissed or not with a "close" button and are displayed on top of the page.
I would like to propose an additional set for messages that provide in-line contextual notifications.
In-line Banners, are less obtrusive and are placed on a particular area of a page or on top of a component they relate to. They persist until the issues are resolved.

**Closed as completed** 2021-06-03 17:32 UTC
Labels: ux-design, cart-validation, api-dependency, starting-2021-Q1
