### ISSUE TITLE
Doesn't receive the promo coupon on order confirmation page

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#14984] opened 2022-02-09 19:06 UTC
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Go to electronics storefront
Enable coupon BUYMORE16 and publish it. 
Add a product that's more than $300 to cart
Place the order

**Actual Result**
The promotion says it will award me with a coupon and I remember, in the past, it would give the coupon on the order confirmation page. But nothing this time. 
<img width="712" alt="Screen Shot 2022-02-09 at 1 53 14 PM" src="https://user-images.githubusercontent.com/45409515/153271843-f8729992-cce8-4da0-a7d0-ec56963eefe3.png">

<img width="1035" alt="Screen Shot 2022-02-09 at 1 54 18 PM" src="https://user-images.githubusercontent.com/45409515/153271999-1e02ba7b-44df-4ad5-91cd-0079f5248427.png">

<img width="1033" alt="Screen Shot 2022-02-09 at 1 54 25 PM" src="https://user-images.githubusercontent.com/45409515/153271923-befd7f1d-255a-4d3f-b0d2-7eb748fbd6ea.png">

**Comment by dydome** [comment] 2022-03-15 10:09
@KateChuen coupon code BUYMORE16 is not working anymore. May you please reverify it?

**Comment by KateChuen** [comment] 2022-03-15 17:03
@dydome The coupon needs to be activated in backoffice. But I'll reverify regardless.

**Comment by KateChuen** [comment] 2022-03-16 19:11
Still able to reproduce the issue.

**Comment by Dalvir-Personal** [comment] 2022-03-25 16:08
@KateChuen We were wondering if if the coupon code was part of the green text that's shown in the screenshot or was is displayed in a different component/section?

**Comment by KateChuen** [comment] 2022-03-25 16:10
Before, when the coupon and promotion is published, and you place an order of >$300, on the order confirmation page, you get the coupon "BUYMORE16" displayed. 
This way, as a user, you know you have this coupon you can use next time.

**Comment by Dalvir-Personal** [comment] 2022-03-25 16:19
It seems like the issue is from backend. @KateChuen is going to look into it.

**Comment by KateChuen** [comment] 2022-03-25 18:41
Created backend ticket https://jira.tools.sap/browse/CXEC-9522

**Comment by Xymmer** [comment] 2022-04-24 14:37
CXEC ticket was sent back to spa team, investigating.
closing this one as it's now https://jira.tools.sap/browse/CXSPA-213

**Closed as completed by Xymmer** 2022-04-24 14:37 UTC
Labels: bug, Major
