### ISSUE TITLE
Oversized banner at the bottom of the search results

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#10459] opened 2020-12-16 22:13 UTC
**Describe the bug**
While editing consents , clicking "select all" generates an error.

**Tell us the version of Spartacus**

test env https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/ (see #10030)

**Steps to reproduce:**

I used Chrome on Windows desktop.

* search for a term, like "[Battery](https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/search/battery)"
* Scroll down the results page
* Bug: see the oversized banner at the bottom of the result list

**Expected behavior**
correctly sized banner

**Error screenshot:**
![screencapture-spartacusstore-cg79x9wuu9-eccommerc1-p5-public-model-t-myhybris-cloud-electronics-spa-en-USD-search-battery-2020-12-16-16_46_02](https://user-images.githubusercontent.com/7065346/102412771-ec433e80-3fc1-11eb-888b-50be013725ea.png)

**Comment by hackergil** [comment] 2020-12-16 22:24
Same happens on iphone safari (large)

**Comment by bgambocjaviniar** [comment] 2021-01-11 19:33
duplicate of https://github.com/SAP/spartacus/issues/10024

re-open if we want to re-size, but removing because of above ticket. But if we are to re-size, it will be done in the PR in the ticket above

**Closed as completed by bgambocjaviniar** 2021-01-11 19:33 UTC
Labels: bug, styling
