### ISSUE TITLE
[requires validation] How to migrate from componentSelectorFactory 

### ISSUE THREAD

**Issue by santoshyadavdev** [SAP/spartacus#6897] opened 2020-03-12 10:08 UTC
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  2.0.0-next.0
- Browser: 
- OS: 
- Device: 
- Other environment details: 9.0.6

## Steps to Reproduce

use ng update to update the @spartacus/core @spartacus/storefront

## Observed Results

Getting error :

Property 'componentSelectorFactory' does not exist on type 'typeof import("D:/Ebbok/Code/pompeius/node_modules/@spartacus/core/src/cms/store/selectors/cms-group.selectors")'. Did you mean 'componentsSelectorFactory'?

## Expected Results
as per https://github.com/SAP/cloud-commerce-spartacus-storefront/commit/ee0707a4ce8bc51d62527b6fb2082337af0b96a3#diff-bec911382ac96c48ca62c06a8193fe7dL74 the above method is deprecated.
as we are not passing the cotext in existing code, it should be either optional or provide the doc to update the same

## Offer to Fix

Yes may need some help.

**Comment by Xymmer** [comment] 2020-04-23 23:48
To dev: please validate if this is a real bug, or not already fixed in later 2.0 'next' release.

**Comment by dunqan** [comment] 2020-05-14 11:09
As components can be restricted per context, context is required in `componentsSelectorFactory` to provide correct results, so can't be optional in this low level (store/selectors) API. 
You should either update your code, or pass current context, which is exactly what we do in facade (high level api) where context is indeed optional.

Third way (but not recommended because of above reasons) is to use `componentsDataSelectorFactory` which grabs only the data, ignoring context.

**Closed as completed by dunqan** 2020-05-14 11:09 UTC
Labels: bug, team/obelix

**Comment by Xymmer** [comment] 2020-05-14 11:52
closing as not a bug
