### ISSUE TITLE
Set Language/Currency in the first time should not emit "LanguagChange" or "CurrencyChange" action

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#911] opened 2019-01-16 14:25 UTC
When "setLauange" and "setCurrency" are called, actions "LanguagChange" and "CurrencyChange" are returned from effects. "LanguageChange" and "CurrencyChange" will cause some data refreshed. So, when "setLanguage" and "setCurrency" called the first time (in function `initialized`), actions "LanguagChange" and "CurrencyChange"  should not be returned.

**Comment by Xymmer** [comment] 2019-01-23 14:48
this is not broken but would speed up things a bit

**Comment by Platonn** [comment] 2020-05-06 13:05
Duplicate of #6900 and already fixed there

**Closed by Platonn** 2020-05-06 13:05 UTC
Labels: MUST, bug, improvement, performance, team/gladiators
