### ISSUE TITLE
Broken e2e regression/anonymous-consents/anonymous-consents-flow.e2e-spec.ts

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#10377] opened 2020-12-11 11:03 UTC
### Test
`regression/anonymous-consents/anonymous-consents-flow.e2e-spec.ts`

### Jenkins job
`spartacus-regression-tests-2005`

### Runs
- `#4​57` - Dec 11, 2020 7:26 AM
- `#4​56` - Dec 10, 2020 7:26 PM

**Comment by plabadie** [comment] 2020-12-11 23:04
It looks like the issue is the test flakiness.  I got the test to pass against develop + dev0, but it does not always pass.
So far, the reason for the flakiness isn't clear.  There might be multiple causes.
- the code to navigate to the home page should be improved and doesn't seem to work well anymore.  Int relies on the title of the link on the logo and the title doesn't seem to be there anymore.
- on logout, I get a session expired error when running the test on the command line.  The redirects to the login page and breaks the test.

**Comment by Platonn** [comment] 2020-12-14 10:41
Duplicate of #10389

**Comment by plabadie** [comment] 2020-12-14 14:46
Closing.  Duplicate of #10389

**Closed as completed by plabadie** 2020-12-14 14:46 UTC
Labels: e2e-tests, anonymous-consent
