### ISSUE TITLE
Cyclic duplication of route parameters when going to the page of the old Storefront (IE)

### ISSUE THREAD

**Issue by RomanTikhonov** [SAP/spartacus#8925] opened 2020-09-15 18:15 UTC
**Describe the bug**
In Internet Explorer, when you go from the page of Spartacus-version to the page of the old Storefront (JSP-based), the country and currency parameters are cyclically added to URL  (that is, `http://localhost:4200/ru/ru/shoppingrulepage` turns into `http://localhost:4200/ru/ru/ru/ru/shoppingrulepage`, then into `http://localhost:4200/ru/ru/ru/ru/ru/ru/shoppingrulepage`, etc.). Other browsers don't have this problem.

**To Reproduce**
1. Open any page in Spartacus-version (e.c. main page http://localhost:4200).
2. Go to any page of the old Storefront version.

**Expected behavior**
The url not mutated.

**Desktop:**
 - OS: Windows 10
 - Browser: Internet Explorer 
 - Version: 11

**Additional context**
The config of context (SiteContextConfig) is correct, urlParameters: ['country', 'language'].

**Comment by Xymmer** [comment] 2020-09-16 21:49
IE11 is not supported by Spartacus. We'll do a quick check into the code to see if there is a workaround that can help.

**Comment by RomanTikhonov** [comment] 2020-09-17 07:02
@Xymmer, I understand this, we discussed this with @tobi-or-not-tobi and it was decided to create a ticket here. In any case, we'll be very grateful for any prompt help in this matter!

**Comment by Xymmer** [comment] 2020-09-30 13:44
waiting for info on this one

**Comment by RomanTikhonov** [comment] 2020-10-02 10:30
> 
> 
> waiting for info on this one

I answered @Platonn in Slack.

**Comment by artem-zur** [comment] 2020-10-08 07:01
Hey guys, @RomanTikhonov, @Platonn!

If you don't mind, maybe you can share some details of private conversations, I believe it can be helpful for other members of Spartacus community (especially who also try to adapt Spartacus-based application for IE 11).

Thanks in advance!

**Comment by Xymmer** [comment] 2021-01-11 20:52
asking @Platonn to comment

**Comment by Platonn** [comment] 2021-01-12 14:38
I was waiting for enough information. Today Roman told me today he's not interested anymore in having the issue solved. 

Many things can contribute to the problem and without knowing the full picture it's hard to guess what's the reason. There are many layers to consider:
- the web server that serves both Spartacus and Accelerator may have high-level custom rules for URL rewrites, redirects and routing.
- Accelerator app may have custom rules for redirects and routing (the generic redirect rules but also site-context related ones)
- Spartacus (Angular) may have custom rules for redirects and routing (generic and side-context related).
- There may be some customizations to the site-context logic either or both in Spartacus and Accelerator 

@artem-zur  If you're having similar issue as Roman reported, would you mind providing more details about your specific case, touching all the layers of routing, redirect rules and site context customizations?

**Comment by artem-zur** [comment] 2021-01-14 18:47
@Platonn, unfortunately we haven't faced this issue on our project, but we have strict requirements to support IE, so maybe in future we will also see the same on our side. I definitely add if will have something in future.

**Comment by Platonn** [comment] 2021-01-18 14:04
Ok, closing for now. Please create a new ticket whenever you can reproduce and link to this ticket.

**Closed as completed by Platonn** 2021-01-18 14:04 UTC
Labels: bug, team/blamed, needs-refinement, ie11
