### ISSUE TITLE
No navigation present in SSR mode (javascript disabled)

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#2743] opened 2019-05-28 19:37 UTC
Only when javascript is disabled. I don't know if this is considered a bug or something that has to be included on the static version of the site.

**Comment by dunqan** [comment] 2019-06-10 06:25
We use mobile first approach also for SSR, so because of the fact, that we have some dynamic layout logic in JS relying on browser width, slots that are not displayed in mobile are not rendered in SSR.
So comparing noJS SSR desktop view to desktop view might show differences. Please compare mobile versions instead.

**Comment by tobi-or-not-tobi** [comment] 2019-09-20 12:00
Yes, this is a bug. 

Our SSR (nowadays at least) only exposes the DOM structure, no HTML. The screen-size driven responsive CSS is applied on top of this. There is however a very small piece in Spartacus that renders a different DOM based on the device/screen-size, which is caused by the LayoutConfig: the header with the navigation will be rendered differently. 
Normally you would not experience this in the browser, because whenever resizing the browser, the DOM got re-rendered. In this case however, the SSR response will not be re-rendered as long as the user doesn't change the screen size. If the user just loads the SSR response, it will likely only show the mobile DOM, with the desktop CSS. 

Solution: we need to (re)render the DOM when the layout is rendered (`PageLayoutService`).

**Comment by qjimmy** [comment] 2019-09-24 19:39
**Muhammad: ** If we desire the navigation to be present in SSR mode, then we need to find a CSS only approach to presenting it. With JS disabled, it severely limits the experience in terms of navigation and in it’s current state, it simply will not function regardless of whether we use the PageLayoutService to render the DOM or not.

**Comment by Xymmer** [comment] 2020-06-27 16:16
need to decide officially we don't support js-disabled

**Comment by tobi-or-not-tobi** [comment] 2021-02-18 10:57
After discussion, closing this bug, and refer to a new feature that we like to add. There are basically 2 directions to improve this: 
- #11186 loading the navigation component in SSR (and change hiding from JS to CSS).
- #9086 use bot detection inside SSR to serve the right rendered page to the right audience.

**Closed by tobi-or-not-tobi** 2021-02-18 10:57 UTC
Labels: bug, ssr, team/blamed
