### ISSUE TITLE
ActiveCartService.requireLoadedCart doesn't return Observable if cart is deleted

### ISSUE THREAD

**Issue by ESchuderer** [SAP/spartacus#13780] opened 2021-09-17 15:46 UTC
Steps to reproduce:
- Authenticate with any given user
- Ensure the user has an active cart
- Delete all the users carts in SAP Commerce
- Ensure ActiveCartService.requireLoadedCart (eg. adding an entry to the cart)

Expected behaviour:
- A new cart is created

Observed behaviour:
- ActiveCartService.requireLoadedCart does not return an Observable

Workaround:
- delete localStorage, especially spartacus⚿{{BASESITE}}⚿cart which contains the active cart id

**Comment by Xymmer** [comment] 2021-11-01 19:29
Hey Patrick, can you consider this scenario and if it will be fixed with cart library?

**Comment by hackergil** [comment] 2021-12-06 20:40
@ESchuderer I've looked into this issue. Whilst I was able to reproduce it, I don't think the problem is that you don't get an observable back. If you call the aforementioned method by adding a cart entry (or any other method), you can get the observable appropriately. but then, the problem is that the OCC call to add entry fails (since there is no cart in the backend anymore) and we don't handle such error appropriately.

That said, can you specify in which business scenario is this a problem? We think that deleting carts from CX is an edge case, and whilst we should handle it in a better way, it's not a bug but an improvement. Maybe you can create a new ticket for such improvement with the information required above?

**Comment by ESchuderer** [comment] 2021-12-06 20:52
Sounds fine to me, maybe you can switch the bug label with improvement?

**Comment by WeizhengSap** [comment] 2022-01-13 14:27
To test it:
In "addToCart()" function of `AddToCartComponent`, we can duplicate `this.activeCartService.addEntry(this.productCode, quantity);` several times, so that when click button, function `addEntry` will be called multiple time. Using this way, we can test whether the function behaviour stable for concurrent calls.
We need consider 4 conditions: user login, cart is in backend, `cartId` is stored in browser, `cart-lib` loaded before. So, there are 16 use cases. 

| user login  | cart is in backend | cartId is stored in browser | cart-lib loaded before | pass | note |
| -----------| ------------------ | -------------------------- | ---------------------- | ---- | ----- | 
| 0  | 0  | 0 | 0 | yes   |
| 0  | 0  | 0 | 1 |  yes |
| 0  | 0  | 1  | 0 | yes | need comment out mini-cart |
| 0  | 0  | 1  | 1 | yes |
| 0  | 1  | 0 | 0 | yes |
| 0  | 1  | 0 | 1 | yes |
| 0  | 1  | 1 | 0 | yes | comment out mini-cart, new active cart created |
| 0  | 1  | 1 | 1 | yes |
| 1  | 0  | 0 | 0 | yes | comment out mini-cart and wish-list |
| 1  | 0  | 0 | 1 | yes |
| 1  | 0  | 1 | 0 | yes | comment out mini-cart and wish-list |
| 1  | 0  | 1 | 1 | yes | see "cart not found" error |
| 1  | 1  | 0 | 0 | yes | comment out mini-cart and wish-list |
| 1  | 1  | 0 | 1 | yes |
| 1  | 1  | 1 | 0 | yes | comment out mini-cart and wish-list |
| 1  | 1  | 1 | 1 |  yes |

**Closed as completed** 2022-01-21 16:05 UTC
Labels: bug, cart, Major, cart-lib, Should
