### ISSUE TITLE
Consents displayed in Safari become out of sync with server value when removing consent

### ISSUE THREAD

**Issue by merterpam** [SAP/spartacus#6269] opened 2020-01-27 17:48 UTC
## Environment Details

- Spartacus:  https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com
- Browser: Safari, 13.0.4
- OS: macOS Catalina 10.15.2

## Steps to Reproduce

1. Register with a new user

![Screenshot 2020-01-27 at 17 38 35](https://user-images.githubusercontent.com/7472949/73195008-67430280-412d-11ea-9f9c-d95f2af3c34a.png)

2. Go to consent management and select all consents by clicking "Select All"

![Screenshot 2020-01-27 at 17 39 20](https://user-images.githubusercontent.com/7472949/73194912-34007380-412d-11ea-97c3-b3e0309288b7.png)

3. Logout, as an anonymous user select all consents by clicking "Select All" at the footer.

![Screenshot 2020-01-27 at 17 39 32](https://user-images.githubusercontent.com/7472949/73194890-29de7500-412d-11ea-90dc-e3d38d1f2da3.png)

4. Sign in back, go to Consent Management Page.

![Screenshot 2020-01-27 at 17 39 20](https://user-images.githubusercontent.com/7472949/73194912-34007380-412d-11ea-97c3-b3e0309288b7.png)

5. Click Clear All, there'll be a pop-up saying that the consents are withdrawn, but in the consent management component the consents will stay checked.

![Screenshot 2020-01-27 at 17 31 58](https://user-images.githubusercontent.com/7472949/73194962-49759d80-412d-11ea-95e7-3e00bc8f2f6a.png)

6. Clicking Clear All will lead to error, as the consents are removed in CX Commerce, but the state is not correctly updated in Spartacus

![Screenshot 2020-01-27 at 17 33 23](https://user-images.githubusercontent.com/7472949/73194973-509cab80-412d-11ea-9eb9-d95f6400e3a0.png)

## Observed Results

After interacting with anonymous consent management banner, My Account Consent Management page is not able to update consents visually correctly.

## Expected Results
Interacting with anonymous consent management banner should not break the functionality of My Account Consent Management page.

**Comment by znikola** [comment] 2020-02-05 15:51
Works on dev12.
Possible reason for not working on the specified server (https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com) is because the back-end is outdated most likely.

Please use dev12 to test again.

**Comment by KateChuen** [comment] 2020-02-05 19:02
I was able to reproduce it on dev12, safari. 

At step5, when we do clear all, the consents remain checked. 
So, at step6, when we do clear all again, we get an error.

**Comment by merterpam** [comment] 2020-02-06 07:55
> Possible reason for not working on the specified server (https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com) is because the back-end is outdated most likely.
The request is sent and executed in the back-end, however the response is somehow not handled correctly, leading a discrepancy between front-end and back-end (i.e. in Hybris consents are cleared while in SPA it's shown as checked and gives the option to clear again which causes the error at Hybris).

> Please use dev12 to test again.
I only have access to public servers. if it's public, can you send the link?

> At step5, when we do clear all, the consents remain checked.
Yes, that seems to be the main problem

**Comment by mirkosoft** [comment] 2020-03-20 11:52
Once it's fixed pls merge it to latest maintenance branch too (1.5.1)

**Comment by LTiger14** [comment] 2020-04-29 19:45
This issue is caused by a backend caching issue that has been fixed in 2005. As of 1905 the `consenttemplates` request that contains the status of the consents is cached in browser for 120 seconds. Safari is the only browser to actually used this cached value despite the `cache-control` header in the request stating it should disregard this cached content.

**Comment by Xymmer** [comment] 2020-04-29 22:04
Hi @merterpam! Our conclusion: works with 2005, issue is seen in 1905, and isn't Spartacus issue. If this fix must be backported to 1905, please create an SAP Commerce support ticket and reference ticket RAY-329.

**Closed by Xymmer** 2020-04-29 22:04 UTC
Labels: MUST, anonymous-consent, backend-dependency, bug, team/gladiators
