### ISSUE TITLE
Product list component loaded twice

### ISSUE THREAD

**Issue by MedKhaldiConfo** [SAP/spartacus#15023] opened 2022-02-15 15:12 UTC
**Describe the behavior :** 

Sometimes when using SSR on CCV2, the product list component seem to be loaded twice.
When checking OCC calls, one search call is done to backend.

For our case, we created our custom **ProductListComponent** because we need to normalize the model returned as response 

**product-list.component.ts  :** 
![image](https://user-images.githubusercontent.com/90682394/154091102-f4c3a5ab-7952-4d7f-bb18-781668d8c6ff.png)

product-list.component.html (async part)
![image](https://user-images.githubusercontent.com/90682394/154091834-31fe69cb-d0bf-4d19-af25-72f6cc989b08.png)

**Desktop:**

1.   Chrome,
2.    Firefox

**Versions:**
1. Angular: 10.2.4
2. Spartacus Libraries: 3.2.1

This modification done on Product List component follow SSR Coding Guidelines ?

**Comment by Xymmer** [comment] 2022-02-17 20:26
@znikola is this related to the fix you are doing for flicker on SSR on product list? or it's different

**Comment by znikola** [comment] 2022-02-18 12:04
Hi,
Thank you for reporting the issue. It looks like a duplicate of https://github.com/SAP/spartacus/issues/14770, which we aim to fix for 5.0

**Comment by Xymmer** [comment] 2022-02-20 15:44
closing as duplicate

**Closed as completed by Xymmer** 2022-02-20 15:44 UTC
Labels: bug, duplicate
