### ISSUE TITLE
Blue theme - my account menu has bad contrast and it is hard to read

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#13137] opened 2021-07-16 09:20 UTC
**Describe the bug**
My account menu is hard to read as it has white color on light grey background

**Tell us the version of Spartacus**
- Library version: 4

**To Reproduce**
1. Login
2. Look at My Account menu

**Expected behavior**
Should have different color with bigger contrast with the background

**Screenshots**
![image](https://user-images.githubusercontent.com/18736434/125924736-1608d16a-7767-4db9-af17-75590d0754bb.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Edge

**Comment by bgambocjaviniar** [comment] 2021-07-16 12:54
duplicate of https://github.com/SAP/spartacus/issues/13124

**Closed as completed by bgambocjaviniar** 2021-07-16 12:54 UTC
Labels: styling, Minor
