### ISSUE TITLE
Layout breaks on release next.5

### ISSUE THREAD

**Issue by bit-dragon** [SAP/spartacus#9505] opened 2020-10-23 18:47 UTC
**Describe the bug**
Layout breaks on next.5 release, basically all pages are not having the correct layout but after refreshing the page the layout is correct.
You can easy replicate this issue by login/logout into the application and navigation to a different section from the user drop-down

**To Reproduce**

[First scenario]
1. Go to home
2. Click on Sign In/Register button
3. Login form does not have the correct layout

[Second Scenario]
1. Go to home
2. Click on Sign In/Register button
3. Fill the form with admin credentials
4. After being redirected to home page the images are so small

[Third Scenario]
1. Go to home
2. Click on Sign In/Register button
3. Fill the form with admin credentials
4. Click on the my account drop-down
5. Select "My Company" option
6. Icons are filling the whole screen, page doesn't have the menu and footer doesn't have correct styles

**Expected behavior**
Every section should have the correct layout and colors.

**Screenshots**
![Capture-home-after-login](https://user-images.githubusercontent.com/1533108/97042109-29e19900-1536-11eb-9771-1786e5f090b8.PNG)
![Capture-login-break](https://user-images.githubusercontent.com/1533108/97042118-2cdc8980-1536-11eb-9f81-2fd1eb2812ef.PNG)
![Capture-my-company-page](https://user-images.githubusercontent.com/1533108/97042214-4f6ea280-1536-11eb-8830-b8188eb2adf4.PNG)

**Desktop (please complete the following information):**
 - OS: Windows [WSL Ubuntu 24]
 - Chrome
 - Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by bgambocjaviniar** [comment] 2020-10-24 02:39
This is a known issue. Will be closing this as it's a duplicate of https://github.com/SAP/spartacus/issues/9440.

**Closed as completed by bgambocjaviniar** 2020-10-24 02:39 UTC
