### ISSUE TITLE
title bar not visible underneath main nav bar in mobile view (works on real iphone but not using desktop in mobileview)

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#7728] opened 2020-05-21 14:43 UTC
**Describe the bug**
The main navigation background overlay is blocking the topnav bar's information like the logo, search icon, and the cart

**To Reproduce**
1. switch to mobile view using your phone or your browser to simulate mobile view
2. click on the main navbar (the hamburger)
3. we can not see the information on the top navbar (header)

**Expected behavior**
To be able to see the logo, search icon, and the cart icon as shown below

**Screenshots**
<img width="299" alt="Screen Shot 2020-05-21 at 10 38 13 AM" src="https://user-images.githubusercontent.com/29099466/82570684-e9798b80-9b4f-11ea-8add-1951d49ded21.png">

**Comment by Xymmer** [comment] 2020-05-22 15:40
This probably works as designed. We're planning a mobile ux overhaul in second half of 2020, so will close this one for now since I can still close the menu and click the search.

**Comment by Xymmer** [comment] 2020-05-22 16:00
reopening to test android for transaprency to be working

**Comment by Xymmer** [comment] 2020-05-22 16:29
works, just not for local, closing

**Closed as completed by Xymmer** 2020-05-22 16:29 UTC
Labels: bug
