### ISSUE TITLE
SmartEdit doesn't show custom template

### ISSUE THREAD

**Issue by rpisarew** [SAP/spartacus#13682] opened 2021-09-10 15:30 UTC
**Describe the bug**
I have a custom template for the home page like this:

```html
<cx-page-slot class="page-fold" position="Stage"></cx-page-slot>
<cx-page-slot position="Content1"></cx-page-slot>
<cx-page-slot position="Content2"></cx-page-slot>

<div class="stories">
  <cx-page-slot position="Tile1"></cx-page-slot>
  <cx-page-slot position="Tile2"></cx-page-slot>
  <cx-page-slot position="Tile3"></cx-page-slot>
  <cx-page-slot position="Tile4"></cx-page-slot>
  <cx-page-slot position="Tile5"></cx-page-slot>
  <cx-page-slot position="Tile6"></cx-page-slot>
  <cx-page-slot position="Tile7"></cx-page-slot>
  <cx-page-slot position="Tile8"></cx-page-slot>
</div>

<cx-page-slot position="Content3"></cx-page-slot>
<cx-page-slot position="Teaser"></cx-page-slot>
<cx-page-slot position="SocialMedia"></cx-page-slot>
```

And this config for the routes:
```typescript
@NgModule({
  declarations: [HomePageComponent],
  imports: [
    PageSlotModule,
    RouterModule.forChild([
      {
        path: '',
        component: HomePageComponent,
        canActivate: [CmsPageGuard],
      },
    ]),
  ],
})
export class HomePageModule {}
```

If I open the page without SmartEdit, everything looks as expected. But when I open the page in SmartEdit, my custom template is ignored and Spartacus just render the slots in the same order as it get's it from the backend. When I click in the preview mode on a link which is the same route, then it shows my custom template.

If I extend my routes config to this:
```typescript
@NgModule({
  declarations: [HomePageComponent],
  imports: [
    PageSlotModule,
    RouterModule.forChild([
      {
        path: '',
        component: HomePageComponent,
        canActivate: [CmsPageGuard],
      },
      {
        path: 'cx-preview',
        component: HomePageComponent,
        canActivate: [CmsPageGuard],
      },
    ]),
  ],
})
export class HomePageModule {}
```

It works as expected, but that does not look right for me. Do I have to create every time a second route with the 'cx-preview' for every page where I have a custom template?

**Tell us the version of Spartacus**
- Spartacus v. 4.0.1
- Hybris: 2011.10

**Comment by WeizhengSap** [comment] 2021-11-01 20:18
If you have a custom template, it's better to change it from CMS data in backend. `cx-preview` knows nothing about which page should go. Spartacus sends a request to Smartedit (like this: `https://localhost:4200/electronics-spa/en/USD/cx-preview?cmsTicketId=647867848787044820cde287-09a9-4d14-a4ab-e124f27ff504`) to get CMS page data and use `PageLayoutComponent` to render it.

```
const cmsRoute: Route = {
  path: '**',
  canActivate: [CmsPageGuard],
  component: PageLayoutComponent,
};
```

**Comment by Xymmer** [comment] 2021-11-01 22:58
Hi @RPisarew, so we think it's not a bug. Closing as such but let me if you think otherwise.

**Closed as completed by Xymmer** 2021-11-01 22:58 UTC
Labels: bug, smartedit
