### ISSUE TITLE
Unable to find "Wishlist" link in My Account dropdown in Spartacus 3.0.0-next.4

### ISSUE THREAD

**Issue by Ajaykumarkonda** [SAP/spartacus#9419] opened 2020-10-20 08:34 UTC
**Describe the bug**
Once I have updated the backend 2005. I Couldn't find Wishlist link in My Account dropdown in Spartacus 3.0.0-next.4.
**To Reproduce**
1. Go to Power tools and login with user
2. Hover on My Account dropdown from right side
3. Couldn't find "Wishlist" selection in list of items. 

**Expected behavior**
Wishlish link need to be present.

**Screenshots**
![missing wishlist](https://user-images.githubusercontent.com/23554781/96560836-6dd96180-12dc-11eb-8ffa-cf141302f771.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome]
 - Version [e.g. 86.0]

**Smartphone (please complete the following information):**

**Additional context**
Wishilst is not showing up in dropdown Once I have updated the "spartacussampledata"
Can I know Wishlist is deprecated in latest version or Did I miss any updates in backend 2005?

**Comment by Xymmer** [comment] 2020-10-23 15:00
moving to future
for our first release, Spartacus powertools won't have a wishlist, as we have a somewhat-competing b2b feature coming, saved carts. but we'll discuss putting it back in at a later date
you could add it yourself but updating your cms data to include that component
and it will still work with electronics storefront

**Comment by Xymmer** [comment] 2020-12-15 15:52
closing as not a bug, as we purposely removed wish list from b2b
will put it back in a new task

**Closed as completed by Xymmer** 2020-12-15 15:52 UTC
Labels: bug, wish list, b2b-storefront
