### ISSUE TITLE
Fix e2e regression/apparel-checkout-as-guest.ts

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9152] opened 2020-10-02 16:20 UTC

**Comment by Platonn** [comment] 2020-10-06 12:43
Todays run was green. See:
- https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-2005/333/
- https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-2005/

We need to identify why this test sometimes fails.
Then we should decide whether we need to fix it immediately vs. mark the sometimes-failing part as flaky.

**Comment by Matejk00** [comment] 2020-10-08 11:21
This test is passing every time so far since we fixed regressions running in nightly builds and seems to not be even flaky. 

I checked all console outputs of latest error builds and this test was always failing along with all others. 
Also I run it locally several times and every time was green.

Maybe we put it on the spot, because appears as a first in jenkins console log before `Full Log` is clicked, so might little bit misleading and pointing it as a reason of build failures.

For now I think we can close this ticket.

**Closed as completed by Matejk00** 2020-10-08 11:21 UTC
Labels: e2e-tests
