### ISSUE TITLE
SmartEdit settings are not applied when it's not on the same domain with storefront (cross origin).

### ISSUE THREAD

**Issue by danilchican** [SAP/spartacus#6125] opened 2020-01-17 07:43 UTC
Hi all!

I've faced with the issue on a cluster.
We have storefront on first domain and Hybris backoffice/hac/**smartedit** on another one.

**The issue**:
When I tried to change settings (e.g. Content Catalog, Product Catalog, Date) in SmartEdit, it's are not applied. But I see valid response with valid key/value pairs for the requests.

**BUT:** It's not reproduced when the storefront and backoffice/hac/smartedit on the same domain.
And in case when I **refresh the page in a browser** I can see **applied settings**.

Pay attention that I followed the instruction below:
https://help.sap.com/viewer/86dd1373053a4c2da8f9885cc9fbe55d/6.7.0.0/en-US/143300e1bda8406cb089179c58f59048.html

Do anyone can help me or faced with the same issue?

**Comment by danilchican** [comment] 2020-01-17 08:35
I'm seeing that when I change settings on Home page - it works well. But when I'm on a Gallery Page and after changing settings I see that Iframe url doesn't have **previewServlet** URI anymore. So after call to **previewwebservices/v1/preview** it redirects me to gallery without that URI and Ticket ID.

**Comment by danilchican** [comment] 2020-01-17 12:29
I've found root cause. Loot at `web/app/smarteditcontainer/services/iFrameManager.js:249`
There is a comment:
```
check failing HTML only if same origin to prevent CORS errors. 
if location to reload in new experience context is different from homepage, one will have to first load the home page in preview mode and then access the location without preview mode 
```

**Comment by Xymmer** [comment] 2020-02-11 01:02
Thanks for finding root cause! We’ll look into it.

**Comment by Xymmer** [comment] 2020-05-19 13:04
Hey @danilchican! We took a look and it turns out this is part of SmartEdit core team. The best approach to getting it fixed is by going through SAP Commerce support. I'm closing this issue and will let them know, but to make sure it's officially followed up, contact support. Thanks for reporting this one.

**Closed by Xymmer** 2020-05-19 13:04 UTC
Labels: MUST, blocks-final-2.0, bug, smartedit, team/gladiators

**Comment by Xymmer** [comment] 2020-07-07 21:05
new refresh issue: #8109
