### ISSUE TITLE
Creating/editing a unit causes a 404

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#10037] opened 2020-11-27 12:03 UTC
Browser used: Firefox Dev 84.0b5 (64-bit) (likely not relevant, but didn't double check on other browsers)

To repro:

- login as admin@unitF.sap / 1234
- create a unit
- after creating a unit, you should see an error message (like on the screenshot below). you can also notice a 404 network request

<img width="1680" alt="Screen Shot 2020-11-27 at 13 01 07" src="https://user-images.githubusercontent.com/11561723/100447439-dfad8380-30b0-11eb-9b1e-2d7bce75cbd9.png">

**Comment by znikola** [comment] 2020-11-27 12:06
Update: the same happens when editing.

**Comment by Platonn** [comment] 2020-11-27 12:06
Duplicate of https://github.com/SAP/spartacus/issues/10036

**Closed as completed** 2020-12-07 10:38 UTC
Labels: bug, b2b-mycompany
