### ISSUE TITLE
Cart request sending anonymous user instead of current in CDS 

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#10011] opened 2020-11-25 21:39 UTC
1. Set your environment to run in CDS mode. Set your environment.ts --> CDS --> true, and against dev0-azure
2. Login as any user in electronics
3. add a product to cart
4. Go to any page, and just refresh
5. We get a FORBIDDEN response in the cart request. (We're sending anonymous instead of current)

**Expected behavior**
Cart request sending 'current' and responds back with a 200 OK.

**Screenshots**
<img width="1440" alt="Screen Shot 2020-11-25 at 4 40 54 PM" src="https://user-images.githubusercontent.com/29099466/100284344-0ba7f800-2f3d-11eb-9b8e-547e4cd95025.png">

**Comment by corey-aloia** [comment] 2020-11-26 15:13
It looks like this issue is potentially a timing issue in the ActiveCartService. This issue should be reproducible even without CDS, by subscribing to cart events from the eventlayer. For example `this.eventService.get(CartAddEntrySuccessEvent).subscribe()`

In the `initAticeCart()` method, changing 
```
combineLatest([
        this.userIdService.getUserId(),
        this.activeCartId$.pipe(auditTime(0)),
      ])
```  

 to 

```      
combineLatest([
        this.userIdService.getUserId(),
        this.activeCartId$,
      ])
```  

causes this to go away

**Comment by marlass** [comment] 2020-11-27 10:34
Active cart id must be asynchronous so it can be "unitialized" before it will be initialized with value from localStorage. The problem was that I added the `auditTime` only in this place instead of adding it in the `activeCartId$ observable.

Here is what I propose instead (e2e tests passes)
![image](https://user-images.githubusercontent.com/6259079/100439913-690a8900-30a4-11eb-8bbd-afc7ff5fc1c5.png)

And it looks that it now works in CDS context as well.

**Closed as completed** 2020-12-07 16:08 UTC
Labels: bug, cds, Important/VeryHigh

**Comment by bgambocjaviniar** [comment] 2020-12-09 08:51
Issue has been fixed as it does not occur anymore manually and from jenkins https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-cds/607/

No more errors related to it. 

***Out of scope | not related** - Pipeline for CDS fails for anonymous e2es (most likely due to some config missing as I have tried manually and it passes in CDS mode. Will investigate in another ticket) + cds e2es (which they still have to fix - we pinged them about it already)
