### ISSUE TITLE
product-variant-selector sizes doesn't work with multi-dimensional variants

### ISSUE THREAD

**Issue by mpriewasser** [SAP/spartacus#3368] opened 2019-06-25 06:28 UTC
## Environment Details

- Spartacus:  latest commit from branch feature/apparel-poc
- Browser: Firefox / Chrome

## Steps to Reproduce
1. Go to https://localhost:4200/apparel-uk/en/GBP/Collections/Kids/Maguro-Print-Boardshort-Youth/p/300608428

## Observed Results
Size Selector contains styles instead of sizes
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/36510032/60073270-42faef80-9720-11e9-931b-086108471851.png">

## Expected Results
Size Selector contains sizes.

## Repository Used
https://github.com/SAP/cloud-commerce-spartacus-storefront/tree/feature/apparel-poc

## Offer to Fix
NO

## Additional Information
The bug depends on the order in which the variant options are returned from the backend, which is essentially random. The `product-variant-selector` always takes the first entry from `variantOptionQualifiers`:

<img width="636" alt="product-variant-selector" src="https://user-images.githubusercontent.com/36510032/60074344-f95fd400-9722-11e9-9ea3-6895b1f25660.png">

Instead it should check the qualifier first and use the entry where `qualifier == size`.

**Comment by Xymmer** [comment] 2019-06-25 13:32
multi-dimensional products will be tackled with B2B effort scheduled for Q4
even if we fix this now the checkout won't work

**Comment by mirkosoft** [comment] 2020-12-23 14:53
closing as dupe of #7878

**Closed by mirkosoft** 2020-12-23 14:53 UTC
Labels: MVP, b2b-multid, bug
