### ISSUE TITLE
B2B. Large Low Quality Banner Below PLP Page

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10050] opened 2020-11-27 13:33 UTC
**Steps to reproduce using 3.0 RC1:** 
1. Navigate to Spartacus powertools using Chrome
2. Search for tools
3. Scroll down to footer. 

**Expected results:** 
3. Footer is shown below last product is listed. 

**Actual Results:** 
3. After last product, a large product banner is shown 
3.a Link: https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/#

**Comment by giancorderoortiz** [comment] 2020-11-27 13:34
![Screen Shot 2020-11-27 at 8 30 47 AM](https://user-images.githubusercontent.com/46171897/100454685-6a7b8780-308b-11eb-8c0b-3b4e5d5a8fa7.png)
![Screen Shot 2020-11-27 at 8 31 01 AM](https://user-images.githubusercontent.com/46171897/100454686-6b141e00-308b-11eb-836d-efe12f5fd53a.png)

**Comment by bgambocjaviniar** [comment] 2021-01-11 18:41
duplicate of https://github.com/SAP/spartacus/issues/10024

**Closed as completed by bgambocjaviniar** 2021-01-11 18:41 UTC
Labels: bug, powertools-sample-data
