### ISSUE TITLE
SmartEdit: Make it work with Powertools

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#8006] opened 2020-06-19 13:12 UTC

**Comment by Xymmer** [comment] 2020-10-27 16:58
While you're at it, see #9242

**Comment by LTiger14** [comment] 2020-10-28 12:50
I tried powertools-spa develop (October 28th) with SmartEdit extensively on 2005 and 2011, I didn't find any problems.

**Comment by LTiger14** [comment] 2020-10-28 13:16
#9242 is marked as future since the issue is for financial accelerator sample data.

**Closed as completed** 2020-10-28 13:40 UTC
Labels: team/gladiators, smartedit, b2b-misc, Important/VeryHigh
