### ISSUE TITLE
Flaky test regression/site-context/currency/currency-product-search.flaky-e2e-spec.ts

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#12272] opened 2021-05-04 13:34 UTC

**Comment by bgambocjaviniar** [comment] 2021-05-13 16:57
PR: GH-12436

- Fixes for flaki-ness were done in #12394, which strengthen the test when using siteContextChange
- remove static number and checking only the ¥ as done in other similar fixes for the tests

**Comment by hackergil** [comment] 2021-05-17 15:30
@bgambocjaviniar Can you create a PR and rename the file so that it runs with the rest?

**Comment by bgambocjaviniar** [comment] 2021-05-17 15:42
> @bgambocjaviniar Can you create a PR and rename the file so that it runs with the rest?

yup I changed it on the same PR and it's running on the pipeline 

[cy dashboard ](https://dashboard.cypress.io/projects/k3nmep/runs/15007/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22regression%2Fsite-context%2Fcurrency%2Fcurrency-product-search.e2e-spec.ts%22%2C%22value%22%3A%22%5B%5C%224788bfb1-441b-4f70-98cf-b7e81b19856a%5C%22%5D%22%7D%5D&statuses=%5B%5D)

**Comment by bgambocjaviniar** [comment] 2021-05-17 17:18
closing because it can be seen in develop now too from https://dashboard.cypress.io/projects/k3nmep/runs/15021/specs?utm_source=github

**Closed as completed by bgambocjaviniar** 2021-05-17 17:18 UTC
Labels: e2e-tests, flaky-e2e
