### ISSUE TITLE
cannot send email out when installed warehouse extension

### ISSUE THREAD

**Issue by kate1zheng** [SAP/spartacus#5721] opened 2019-12-10 10:54 UTC
## Environment Details

- Spartacus: 1.3
- Browser: Google Chrome Version 76.0.3809.132
- OS: MacOS jave version 10.14.
- Device: 
- Other environment details: 

## Steps to Reproduce
1. install commerce suite using latest recipe which includes some extensions mentioned in https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5208 
2. start spa which include stock notification/my interests/notification preference functions
3. subscribe an out of stock product
4. change the stock level of the product to make it in stock
5. run cron job stockLevelStatusJob
6. check there is no interests in my interests, it is correct
7. but there is no email to send out

## Observed Results

there is no interests in my interests, it is correct
but there is no email to send out

## Expected Results
the email is send to end user to tell him/her that the product is back in stock
## Offer to Fix
![image](https://user-images.githubusercontent.com/43032959/70523143-5dfdd680-1b7d-11ea-804f-c6191f530a66.png)
the 
the process model should use StockNotificationProcessModel which is sub class of ProductIntererstsProcessModels
because if cannot find the class type strategy, will find all strateties of its parents.

## Additional Information
due to the recipe is changed, and warehouse extension is installed, and warehouse add a new strategy for businessModel
![image](https://user-images.githubusercontent.com/43032959/70523338-cf3d8980-1b7d-11ea-9baa-28bb545a3c10.png)
if cannot find the class type strategy, will find all strateties of its parents.
so when finding strategy, will find 2 strategies - one is ours and another is warehouse's, and the first one will be returned, here returned the one in warehouse
![image](https://user-images.githubusercontent.com/43032959/70523427-02801880-1b7e-11ea-90b2-6179bb1802f0.png)
if change the strategy key to class itself, not it's parent, then it will be found correctly

**Comment by hackergil** [comment] 2021-06-14 18:45
This is not a bug in Spartacus, this is a backend issue. A backend bug ticket should be created and this one should be closed.

**Comment by Xymmer** [comment] 2021-06-14 19:22
created https://cxjira.sap.com/browse/CLC-2891
closing this one

**Closed by Xymmer** 2021-06-14 19:22 UTC
Labels: Major, bug, stock-notification
