### ISSUE TITLE
Terms And Conditions - Hyperlinks not working

### ISSUE THREAD

**Issue by ivan-ilic** [SAP/spartacus#9116] opened 2020-10-01 09:01 UTC
**Describe the bug**
Terms and conditions page consists of 3 paragraph components. In those components, ID attributes are added for hyperlinks. Since cx-paragraph component uses "[innerHTML]" to display component content, ID attributes are not rendered, and hyperlinks are not working. 

**To Reproduce**
To to Terms and Conditions page, hyperlinks in menu are not working so anchors cannot be used to navigate

**Comment by Xymmer** [comment] 2020-10-07 13:45
dupe of #3506 which depends on #915

**Closed as completed by Xymmer** 2020-10-07 13:45 UTC
Labels: bug
