### ISSUE TITLE
[windows tablet][edge] Drop down menus are not reliably responding to touch actions

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#3476] opened 2019-07-01 14:11 UTC
Both the user menu and main menu dropdowns don't work reliably with touch in Edge.
You can have success clicking sometimes, but often it just closes without any action. 

Problem is not present on Chrome. 

![image](https://user-images.githubusercontent.com/5839835/60443003-8ff82d80-9c1a-11e9-8e97-f05578f2f53f.png)

**Comment by kacperknapik** [comment] 2019-07-24 12:44
cannot reproduce

**Comment by Pucek9** [comment] 2019-08-16 09:48
Cannot reproduce on Edge for Galaxy Tab A (Android 8.1.0).

**Comment by morganm58** [comment] 2021-06-21 16:53
Closing because I can not reproduce.

**Closed by morganm58** 2021-06-21 16:53 UTC
Labels: Minor, bug, styling
