### ISSUE TITLE
There are no changes on SmartEdit UI after adding/deleting components

### ISSUE THREAD

**Issue by VBAlexG** [SAP/spartacus#11848] opened 2021-04-07 07:44 UTC
**Describe the bug**
There are no changes on SmartEdit UI after adding/deleting components. This Behavior occurs with the ootb Electronics Store and also in my Customers Project.

**Tell us the version of Spartacus**
Spartacus: 3.1
Hybris/SAP Commerce Cloud: 2011.2

**To Reproduce**
1. Go to the SmartEdit and login as Digital manager
2. Open any page
3. Add or remove component on the page

**Actual behavior**
The changes on the components are only visible after reloading the Page.

**Expected behavior**
Changes should be shown on the page without reloading the Page.

**Screenshots**
No Screenshots

**Desktop (please complete the following information):**
 - OS: Win 10 (Build: 19042.870)
 - Browser: Tested on Chrome and Firefox (latest Versions)

**Smartphone (please complete the following information):**
Not Tested on mobile Devices.

**Additional context**
My Team and our Customer noticed this Issue after upgrading Spartacus from 2.1 to 3.1.

**Comment by J0hn-sOn** [comment] 2021-04-07 12:20
Hello,

i just experienced the same issue on the latest version with a default electronics setup. After modifying a page/component, the view is not refreshed. In the console i could see, that the preview page is not retrieved correctly:

`https://localhost:9002/occ/v2/electronics-spa/cms/pages/$%7Bid%7D?code=homepage&lang=en&curr=USD&cmsTicketId=64783905004161927b757e91-5966-48e7-ab94-290b90688466`

in the url path you can see, that the page ID is not filled properly. there is the placeholder $%7Bid%7D instead. When calling the right url with a browser, i get the correct result.

Hope i could help

**Comment by plabadie** [comment] 2021-04-14 21:16
This SO question his also possibly related
https://stackoverflow.com/questions/67090870/spartacus-page-id-not-resolved-after-changes-from-smartedit

**Comment by jwdwsq** [comment] 2021-05-25 07:32
This has been open for a while. Any timelines when we can expect this bug to be fixed? Any workarounds?

**Comment by Xymmer** [comment] 2021-06-03 12:51
Hi! Sorry for the delay. The refresh with SmartEdit issue can be caused by 3 different scenarios, 2 of which aren't related to Spartacus. A summary of trouble-shooting steps is here: https://sap.github.io/spartacus-docs/smartEdit-setup-instructions-for-spartacus/#troubleshooting

For the issue that is specific to Spartacus, when 3.1 was released, we inadvertently broke SmartEdit refresh, but it's fixed now. See #12100. 

Other reasons for refresh problems are stated in the troubleshooting. There's a caching configuration setting and also SmartEdit itself had an issue with refresh a while back. I'm closing this ticket for now as we've tested it and it's working, but contact me if not.

**Closed as completed by Xymmer** 2021-06-03 12:51 UTC
Labels: bug
