### ISSUE TITLE
The focus jumps to the last group in the group menu after selecting/removing an item with keyboard(return & space key)

### ISSUE THREAD

**Issue by Changsuwan** [SAP/spartacus#11560] opened 2021-03-18 13:55 UTC

**Comment by Uli-Tiger** [comment] 2021-03-24 17:29
same root cause as #11563 and will be fixed together with it

**Comment by Uli-Tiger** [comment] 2021-03-25 09:07
test on team server is missing - can be done tomorrow.

**Closed as completed** 2021-03-29 10:22 UTC
Labels: bug, a11y/keyboard :keyboard:
