### ISSUE TITLE
AddToHomeScreenService can't be imported from the @spartacus/storefront

### ISSUE THREAD

**Issue by blaiseup** [SAP/spartacus#8170] opened 2020-07-10 11:57 UTC
- Spartacus 2.0.3

**Describe the bug**
The `AddToHomeScreenService`, used in the pwa module, is not exported in the index.ts file, so it can not be imported from the `@spartacus/storefront`.

**To Reproduce**
1. Import service in any component

**Expected behavior**
The service should be injected without errors

**Comment by Xymmer** [comment] 2020-07-10 12:22
Fix version is set to 2.1 but make sure to add fix to 2.0.x maintenance

**Comment by janrode** [comment] 2020-07-14 12:02
~Duplicate of #8079~ This ticket has more detailed info about the problem

**Closed as completed** 2020-07-16 11:19 UTC
Labels: bug, add-to-home, public-api, from-community

**Comment by giancorderoortiz** [comment] 2020-08-03 23:14
how to qa?

**Comment by mszczepaniak** [comment] 2020-08-20 09:04
~As far as I see it's only merged to develop, need to be merged also to 2.0.x .~ done

**Comment by kacperknapik** [comment] 2020-08-24 13:04
**QA steps:** import and use `AddToHomeScreenService` from `@spartacus/storefront`, try to build the app and check if the error still appears

**Comment by kacperknapik** [comment] 2020-08-24 15:18
> how to qa?

~**QA steps:** import and use `AddToHomeScreenService` from `@spartacus/storefront`, try to build the app and check if the error still appears~ After some thinking, this ticket doesn't need QA - it's just an import
