### ISSUE TITLE
Consent banner not shown again for updated consent after Logout

### ISSUE THREAD

**Issue by arminh** [SAP/spartacus#14964] opened 2022-02-07 15:32 UTC
**Description**
The problem occurs when a new version of a consent template is created in SAP Commerce while a user is logged in. If the user then performs a logout, the check if the consent template was updated is skipped. This leads to the consent banner not being shown despite the new consent version in SAP Commerce.

**Library version**
4.2.1

**Steps to reproduce the behavior:**
1. Open the Spartacus storefront.
2. Dismiss the consent banner or confirm the consents (doesn't matter)
2. Log in with your credentials
3. In SAP commerce create a new version of an existing consent and expose it
4. In Spartacus perform a logout
5. The consent banner is not shown
6. Refresh the page
7. The consent banner is still not shown

**Expected behavior**
The consent banner should be shown again if a consent was updated in SAP Commerce

**Desktop**
 - OS: Ubuntu 18.04.6 LTS
 - Browser: Google Chrome
 - Version: 98.0.4758.80 (Official Build) (64-bit)

**Additional context**
I investigated the problem a little bit. The issue is the following:

1. "[Auth] Logout"-Action is dispatched which clears the state for "anonymous-consents->templates". 
2. After the logout flow is completed, the "[Anonymous Consents] Load Anonymous Consent Templates"-Action is triggered.
3. The loadAnonymousConsentTemplates$ effect handles the action, but skips the call to detectUpdatedTemplates(...) since the currentConsentTemplates are undefined
4. The new template version is loaded and stored as the current version
5. Since the banner was already dismissed at one point and the updated flag is also false, the banner will never be shown again for the updated template

**Comment by Xymmer** [comment] 2022-02-07 18:46
We think not a bug because it was designed this way. Closing but contact Bill (or reopen) if you want us to consider it as an improvement.

**Closed as completed by Xymmer** 2022-02-07 18:46 UTC

**Comment by arminh** [comment] 2022-02-08 07:14
Could you maybe explain the idea behind that design decision? Because if the user isn't logged (doesn't perform a logout) after a consent template change, they do see the banner again. The behavior seems inconsistent.
