### ISSUE TITLE
TODO in the address details of a unit

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#10039] opened 2020-11-27 12:16 UTC
There's a TODO in the "Address Details"'s title (see the screen shot below):
<img width="1225" alt="Screen Shot 2020-11-27 at 13 14 04" src="https://user-images.githubusercontent.com/11561723/100448510-b0981180-30b2-11eb-953e-052e27d977bc.png">

**Comment by Pucek9** [comment] 2020-11-27 20:37
Duplicate of #9610

**Closed as completed** 2020-12-04 10:24 UTC
Labels: bug, b2b-mycompany
