### ISSUE TITLE
Cannot open PDP of product in browser tab if the name has a dot

### ISSUE THREAD

**Issue by geffchang** [SAP/spartacus#7427] opened 2020-05-03 10:31 UTC
## Environment Details

- Electronics SPA site: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/

## Steps to Reproduce

1. In the search box, search for a product that has a DOT in the name. e.g. EOS 500D + EF-S 18-200mm f/3.5-5.6 IS, kit
2. In the search result, click on the product. The product/PDP will be displayed.
3. Copy the URL of the product in the address bar. e.g. https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/product/2053367/EOS%20500D%20%2B%20EF-S%2018-200mm%20f%2F3.5-5.6%20IS,%20kit
4. Open a new browser tab, and paste/enter the URL.

## Observed Results

404 is displayed. See: https://imgur.com/a/1FWp1hz

This issue happens when you open the URL on a browser tab. However, it doesn't happen if you open the product by clicking it on the site (e.g. PLP / search result)

## Expected Results

The PDP for the product is displayed.

## Offer to Fix

NO

## Additional Information

- Other products that do not have a DOT in the name can be displayed when you open their URLs in a new browser tab. Try with: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/product/358639/DSC-N1
- This issue does not happen on localhost.
- Is the issue I reported a CCV2 issue, rather than a Spartacus / SAP Commerce Cloud issue?

**Comment by Platonn** [comment] 2020-05-05 14:37
It guess it's a server's routing misconfiguration (i.e. handling paths with dots as files `*.*`).

I've checked that it's not because of Spartacus SSR. Locally I can successfully open the Server-Side Rendered page:
http://localhost:4000/electronics-spa/en/USD/product/2053367/EOS%20500D%20%2B%20EF-S%2018-200mm%20f%2F3.5-5.6%20IS,%20kit
So the ExpressJS routing rule isn't guilty: https://github.com/SAP/spartacus/blob/515142f/projects/storefrontapp/server.ts#L35

Perhaps there is some misconfiguration on CCV2. To be verified.

**Comment by Xymmer** [comment] 2020-05-05 22:57
closing as not a bug

**Closed as completed by Xymmer** 2020-05-05 22:57 UTC
Labels: bug, ccv2
