### ISSUE TITLE
checkout-as-persistent-user e2e test failing

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#5730] opened 2019-12-10 16:57 UTC
Test failing consistently over past few days in develop branch. 
Causing confusion as to whether it's error in epic branch being merged or develop. 

(Please fix soon... )

Test screenshots: 

![Checkout - As a Persistent User -- checkout test as a persistent user -- should choose delivery (failed)](https://user-images.githubusercontent.com/46171897/70550687-20308c00-1b44-11ea-853d-8916eadbbc7a.png)

![Checkout - As a Persistent User -- checkout test as a persistent user -- should select payment method (failed)](https://user-images.githubusercontent.com/46171897/70550700-26bf0380-1b44-11ea-8ada-959f191e72ac.png)

![Checkout - As a Persistent User -- checkout test as a persistent user -- should proceed to checkout and select shipping address (failed)](https://user-images.githubusercontent.com/46171897/70550690-232b7c80-1b44-11ea-96c8-7851ee58c12b.png)

Test execution video here: 
[checkout-as-persistent-user.e2e-spec.ts.mp4.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3946123/checkout-as-persistent-user.e2e-spec.ts.mp4.zip)

**Comment by marlass** [comment] 2020-05-08 09:57
Duplicate of #6696

**Closed by marlass** 2020-05-08 09:57 UTC
Labels: e2e-tests
